const SECTION_DEFS={
  history:{icon:"🏛️",zh:"历史",py:"Lìshǐ",en:"History"},
  culture:{icon:"🎭",zh:"文化",py:"Wénhuà",en:"Culture"},
  literature:{icon:"📚",zh:"文学",py:"Wénxué",en:"Literature"},
  culinary:{icon:"🍜",zh:"美食",py:"Měishí",en:"Culinary"},
  nature:{icon:"🏔️",zh:"自然",py:"Zìrán",en:"Nature"},
  business:{icon:"🏭",zh:"经济",py:"Jīngjì",en:"Economy"},
  language:{icon:"🗣️",zh:"语言",py:"Yǔyán",en:"Language"}
};

const REGION_CONTENT={
  110000:{
    history:{zh:"北京是中国的首都，拥有超过三千年的建城史和八百余年的建都史。从辽南京、金中都、元大都到明清京师，北京见证了中国统一多民族国家的形成与发展。",py:"Běijīng shì Zhōngguó de shǒudū, yōngyǒu chāoguò sānqiān nián de jiànchéngshǐ hé bābǎi yú nián de jiàndūshǐ. Cóng Liáo Nánjīng, Jīn Zhōngdū, Yuán Dàdū dào Míng-Qīng Jīngshī, Běijīng jiànzhèngle Zhōngguó tǒngyī duō mínzú guójiā de xíngchéng yǔ fāzhǎn.",en:"Beijing is China's capital with over 3,000 years of city history and over 800 years as capital. From Liao, Jin, Yuan, to Ming-Qing, it witnessed the formation of China as a unified multi-ethnic state."},
    culture:{zh:"北京是全国文化中心，拥有京剧、相声、庙会等丰富的非物质文化遗产。故宫博物院和天坛是世界文化遗产，每年吸引数千万游客。",py:"Běijīng shì quánguó wénhuà zhōngxīn, yōngyǒu jīngjù, xiàngsheng, miàohuì děng fēngfù de fēiwùzhì wénhuà yíchǎn. Gùgōng Bówùyuàn hé Tiāntán shì shìjiè wénhuà yíchǎn, měinián xīyǐn shùqiān wàn yóukè.",en:"Beijing is China's cultural center, rich in Peking opera, crosstalk, and temple fairs. The Palace Museum and Temple of Heaven are UNESCO World Heritage Sites."},
    literature:{zh:"北京是中国现代文学的发源地之一，鲁迅、老舍、沈从文等文学巨匠曾在此创作。当代北京依然活跃着众多文学刊物和作家群体。",py:"Běijīng shì Zhōngguó xiàndài wénxué de fāyuándì zhīyī, Lǔ Xùn, Lǎo Shě, Shěn Cóngwén děng wénxué jùjiàng céng zài cǐ chuàngzuò. Dāngdài Běijīng yīrán huóyùzhe zhòngduō wénxué kānwù hé zuòjiā qúntǐ.",en:"Beijing was a birthplace of modern Chinese literature, home to Lu Xun, Lao She, and Shen Congwen. Contemporary Beijing remains active with numerous literary publications."},
    culinary:{zh:"北京烤鸭是享誉世界的名菜，源自宫廷御膳，以皮脆肉嫩著称。豆汁儿、焦圈、卤煮等老北京小吃也独具风味。",py:"Běijīng kǎoyā shì xiǎngyù shìjiè de míngcài, yuánzì gōngtíng yùshàn, yǐ pí cuì ròu nèn zhùchēng. Dòuzhīr, jiāoquān, lǔzhǔ děng lǎo Běijīng xiǎochī yě dú jù fēngwèi.",en:"Peking duck is a world-renowned dish from imperial cuisine with crispy skin and tender meat. Old Beijing snacks like fermented mung bean drink and fried dough rings have unique flavors."},
    nature:{zh:"北京西部和北部有燕山与太行山余脉，八达岭长城蜿蜒于群山之间。密云水库是北京重要的水源地，生态环境优美。",py:"Běijīng xībù hé běibù yǒu Yānshān yǔ Tàihángshān yúmài, Bādálǐng Chángchéng wānyányú qúnshān zhījiān. Mìyún Shuǐkù shì Běijīng zhòngyào de shuǐyuándì, shēngtài huánjìng yōuměi.",en:"Yanshan and Taihang ranges extend through Beijing's west and north, with the Great Wall at Badaling winding through mountains. Miyun Reservoir is a vital water source."},
    business:{zh:"北京是中国的政治、经济决策中心，总部经济发达。中关村科技园是中国第一个国家级高新技术产业开发区。",py:"Běijīng shì Zhōngguó de zhèngzhì, jīngjì juécè zhōngxīn, zǒngbù jīngjì fādá. Zhōngguāncūn Kējì Yuán shì Zhōngguó dì yī gè guójiā jí gāoxīn jìshù chǎnyè kāifāqū.",en:"Beijing is China's political and economic decision-making center with a strong headquarters economy. Zhongguancun is China's first national high-tech industrial zone."},
    language:{zh:"北京话是普通话的标准语音来源，以儿化音和轻声为特色。北京腔语调抑扬顿挫，是中国最具辨识度的方言之一。",py:"Běijīnghuà shì Pǔtōnghuà de biāozhǔn yǔyīn láiyuán, yǐ érhuàyīn hé qīngshēng wéi tèsè. Běijīngqiāng yǔdiào yìyángdùncuò, shì Zhōngguó zuì jù biànshí dù de fāngyán zhīyī.",en:"The Beijing dialect is the standard phonetic source for Mandarin, featuring erhua and neutral tones. Beijing speech is one of China's most recognizable dialects."}
  },
  120000:{
    history:{zh:"天津意为天子津渡，因明成祖朱棣在此渡河而得名。自1860年开埠以来，天津成为中国北方重要的通商口岸和工业城市。",py:"Tiānjīn yìwéi tiānzǐ jīndù, yīn Míng Chéngzǔ Zhū Dì zài cǐ dùhé ér démíng. Zì 1860 nián kāibù yǐlái, Tiānjīn chéngwéi Zhōngguó běifāng zhòngyào de tōngshāng ànkǒu hé gōngyè chéngshì.",en:"Tianjin means 'Heavenly Ford' named after Emperor Yongle's crossing. Since opening as a treaty port in 1860, it became a major northern commercial port and industrial city."},
    culture:{zh:"天津是中国北方曲艺之乡，相声、快板、京韵大鼓等曲艺形式繁荣兴盛。天津泥人张彩塑和杨柳青年画是民间艺术瑰宝。",py:"Tiānjīn shì Zhōngguó běifāng qǔyì zhī xiāng, xiàngsheng, kuàibǎn, Jīngyùn dàgǔ děng qǔyì xíngshì fánróng xīngshèng. Tiānjīn Nírén Zhāng cǎisù hé Yángliǔqīng niánhuà shì mínjiān yìshù guībǎo.",en:"Tianjin is the northern capital of folk arts, thriving with crosstalk, bamboo clappers, and drum singing. Clay Figure Zhang sculptures and Yangliuqing New Year paintings are folk art treasures."},
    literature:{zh:"天津是中国近代文学的重要阵地，《小说月报》等文学刊物在此创刊。曹禺、孙犁等著名作家诞生或成长于天津。",py:"Tiānjīn shì Zhōngguó jìndài wénxué de zhòngyào zhèndì, Xiǎoshuō Yuèbào děng wénxué kānwù zài cǐ chuàngkān. Cáo Yú, Sūn Lí děng zhùmíng zuòjiā dànshēng huò chéngzhǎng yú Tiānjīn.",en:"Tianjin was an important base for modern Chinese literature. Famous writers like Cao Yu and Sun Li were born or raised here."},
    culinary:{zh:"天津小吃以三绝闻名：狗不理包子、十八街麻花和耳朵眼炸糕。天津人热爱早点文化，煎饼果子是最受欢迎的街头美食。",py:"Tiānjīn xiǎochī yǐ sānjué wénmíng: Gǒubùlǐ bāozi, Shíbā Jiē máhuā hé Ěrduoyǎn zhágāo. Tiānjīn rén rè'ài zǎodiǎn wénhuà, jiānbing guǒzi shì zuì shòu huānyíng de jiētóu měishí.",en:"Tianjin snacks are famous for the 'Three Wonders': Goubuli baozi, Shiba Street twist, and Ear-hole fried cake. Jianbing guozi is the most popular street food."},
    nature:{zh:"天津位于海河下游，东临渤海，拥有153公里海岸线。七里海湿地是候鸟迁徙的重要驿站，栖息着数百种鸟类。",py:"Tiānjīn wèiyú Hǎihé xiàyóu, dōng lín Bóhǎi, yōngyǒu 153 gōnglǐ hǎi'ànxiàn. Qīlǐhǎi shīdì shì hòuniǎo qiānxī de zhòngyào zhànyì, qīxīzhe shùbǎi zhǒng niǎolèi.",en:"Tianjin sits at the lower Haihe River facing the Bohai Sea with 153 km of coastline. Qilihai Wetland is a crucial stopover for migratory birds."},
    business:{zh:"天津是中国北方最大的沿海开放城市，天津港是世界等级最高的人工深水港之一。滨海新区是国家级新区。",py:"Tiānjīn shì Zhōngguó běifāng zuìdà de yánhǎi kāifàng chéngshì, Tiānjīng Gǎng shì shìjiè děngjí zuìgāo de réngōng shēnshuǐgǎng zhīyī. Bīnhǎi Xīnqū shì guójiā jí xīnqū.",en:"Tianjin is northern China's largest coastal open city. Tianjin Port is one of the world's highest-class artificial deep-water ports."},
    language:{zh:"天津话与北京话同属北方方言，但语调更为夸张幽默。天津人说话自带喜感，独特的语音语调使其成为相声艺术的沃土。",py:"Tiānjīnhuà yǔ Běijīnghuà tóng shǔ běifāng fāngyán, dàn yǔdiào gèngwéi kuāzhāng yōumò. Tiānjīn rén shuōhuà zìdài xǐgǎn, dútè de yǔyīn yǔdiào shǐ qí chéngwéi xiàngsheng yìshù de wòtǔ.",en:"Tianjin dialect shares northern roots with Beijing but has more exaggerated and humorous tones, making it fertile ground for crosstalk art."}
  },
  130000:{
    history:{zh:"河北是中华文明的重要发祥地之一，涿鹿之战是传说中黄帝与蚩尤的决战。燕赵大地自古多慷慨悲歌之士。",py:"Héběi shì Zhōnghuá wénmíng de zhòngyào fāxiángdì zhīyī, Zhuōlù zhī zhàn shì chuánshuō zhōng Huáng Dì yǔ Chī Yóu de juézhàn. Yān Zhào dàdì zìgǔ duō kāngkǎi bēigē zhī shì.",en:"Hebei is a birthplace of Chinese civilization, site of the legendary Battle of Zhuolu. The Yan-Zhao land has been known for heroic spirits since ancient times."},
    culture:{zh:"河北有蔚县剪纸、唐山皮影、吴桥杂技等国家级非遗。承德避暑山庄和清东陵是世界文化遗产。",py:"Héběi yǒu Wèixiàn jiǎnzhǐ, Tángshān pǐngyǐng, Wúqiáo zájì děng guójiā jí fēiwùzhì wénhuà yíchǎn. Chéngdé Bìshǔ Shānzhuāng hé Qīng Dōnglíng shì shìjiè wénhuà yíchǎn.",en:"Hebei has national intangible heritage including Weixian paper-cutting, Tangshan shadow puppetry, and Wuqiao acrobatics. Chengde Mountain Resort and Eastern Qing Tombs are UNESCO sites."},
    literature:{zh:"河北是《红楼梦》作者曹雪芹的祖籍地。纪晓岚编纂《四库全书》的故事在沧州广为传颂。",py:"Héběi shì Hónglóumèng zuòzhě Cáo Xuěqín de zǔjídì. Jì Xiǎolán biānzuǎn Sìkù Quánshū de gùshì zài Cāngzhōu guǎng wéi chuánsòng.",en:"Hebei is the ancestral home of Cao Xueqin, author of Dream of the Red Chamber. The story of Ji Xiaolan compiling the Complete Library of Four Treasures is widely celebrated in Cangzhou."},
    culinary:{zh:"河北美食以驴肉火烧最为著名，沧州火锅鸡和保定直隶官府菜也极具特色。坝上地区的莜面窝窝体现了塞外饮食文化。",py:"Héběi měishí yǐ lǘròu huǒshāo zuìwéi zhùmíng, Cāngzhōu huǒguàn jī hé Bǎodìng Zhílì guānfǔcài yě jí jù tèsè. Bàshàng dìqū de yóumiàn wōwo tǐxiànle sàiwài yǐnshí wénhuà.",en:"Hebei is most famous for donkey meat fire-baked buns. Cangzhou hotpot chicken and Baoding Zhili official cuisine are also distinctive."},
    nature:{zh:"河北地形多样，坝上草原辽阔壮美，白洋淀是中国北方最大的淡水湖泊湿地。张家口崇礼是2022年冬奥会雪上项目举办地。",py:"Héběi dìxíng duōyàng, Bàshàng cǎoyuán liáokuò zhuàngměi, Báiyángdiàn shì Zhōngguó běifāng zuìdà de dànshuǐ húpàn shīdì. Zhāngjiākǒu Chónglì shì 2022 nián Dōng'àohuì xuěshàng xiàngmù jǔbàndì.",en:"Hebei has diverse terrain with vast Bashang Grassland and Baiyangdian wetland. Zhangjiakou Chongli hosted the 2022 Winter Olympics snow events."},
    business:{zh:"河北是中国重要的钢铁、建材和化工基地，粗钢产量长期居全国首位。雄安新区是继深圳、浦东之后的又一国家级新区。",py:"Héběi shì Zhōngguó zhòngyào de gāngtiě, jiàncái hé huàgōng jīdì, cūgāng chǎnliàng chángqī jū quánguó shǒuwèi. Xióng'ān Xīnqū shì jì Shēnzhèn, Pǔdōng zhīhòu de yòu yī guójiā jí xīnqū.",en:"Hebei is a major steel, construction materials, and chemical base with the nation's highest crude steel output. Xiong'an New Area is a major national-level development zone."},
    language:{zh:"河北方言属于北方官话，各地口音差异较大。冀中方言保留了较多古汉语词汇，邯郸方言带有中原特色。",py:"Héběi fāngyán shǔyú běifāng guānhuà, gèdì kǒuyīn chāyì jiàodà. Jìzhōng fāngyán bǎoliúle jiào duō gǔ Hànyǔ cíhuì, Hándān fāngyán dàiyǒu zhōngyuán tèsè.",en:"Hebei dialects belong to Northern Mandarin with significant regional variations. Central Hebei preserves many ancient vocabulary words."}
  },
  140000:{
    history:{zh:"山西简称晋，是中华文明的发源地之一，尧舜禹的传说多与此地有关。晋商纵横天下五百年，开创了中国最早的票号金融体系。",py:"Shānxī jiǎnchēng Jìn, shì Zhōnghuá wénmíng de fāxiángdì zhīyī, Yáo-Shùn-Yǔ de chuánshuō duō yǔ cǐdì yǒuguān. Jìnshāng zònghéng tiānxià wǔbǎi nián, kāichuàngle Zhōngguó zuìzǎo de piàohào jīnróng tǐxì.",en:"Shanxi, abbreviated 'Jin,' is a birthplace of Chinese civilization linked to emperors Yao, Shun, and Yu. Jin merchants dominated trade for 500 years, creating China's earliest draft bank system."},
    culture:{zh:"山西是中国古建筑的宝库，现存宋辽金以前木结构古建筑数量居全国之首。云冈石窟和五台山是世界文化遗产。",py:"Shānxī shì Zhōngguó gǔjiànzhù de bǎokù, xiàncún Sòng-Liáo-Jīn yǐqián mù jiégòu gǔjiànzhù shùliàng jū quánguó zhī shǒu. Yúngāng Shíkū hé Wǔtái Shān shì shìjiè wénhuà yíchǎn.",en:"Shanxi is a treasure trove of ancient architecture with the most pre-Song/Jin timber buildings in China. Yungang Grottoes and Mount Wutai are UNESCO World Heritage Sites."},
    literature:{zh:"山西是元曲四大家中三位——关汉卿、白朴、郑光祖的故里。蒲松龄的名著《聊斋志异》与山西也有深厚渊源。",py:"Shānxī shì Yuánqǔ sì dàjiā zhōng sān wèi——Guān Hànqīng, Bái Pǔ, Zhèng Guāngzǔ de gùlǐ. Pú Sōnglíng de míngzhù Liáozhāi Zhìyì yǔ Shānxī yě yǒu shēnhòu yuānyuán.",en:"Shanxi was home to three of the four great Yuan dramatists. Pu Songling's masterpiece Strange Tales from a Chinese Studio has deep Shanxi connections."},
    culinary:{zh:"山西面食文化源远流长，刀削面、剔尖、猫耳朵等面食种类超过280种。山西老陈醋历史悠久，是中国四大名醋之首。",py:"Shānxī miànshí wénhuà yuányuǎn liúcháng, dāoxiāomiàn, tījiān, māo ěrduo děng miànshí zhǒnglèi chāoguò 280 zhǒng. Shānxī lǎo chén cù lìshǐ yōujiǔ, shì Zhōngguó sì dà míng cù zhī shǒu.",en:"Shanxi noodle culture spans millennia with over 280 varieties. Shanxi aged vinegar has a long history, ranked first among China's four famous vinegars."},
    nature:{zh:"山西位于黄土高原东部，太行山与黄河构成了壮丽的自然景观。壶口瀑布是黄河上最壮观的瀑布。",py:"Shānxī wèiyú Huángtǔ Gāoyuán dōngbù, Tàihángshān yǔ Huáng Hé gòuchéngle zhuànglì de zìrán jǐngguān. Húkǒu Pùbù shì Huáng Hé shàng zuì zhuàngguān de pùbù.",en:"Shanxi lies on the eastern Loess Plateau with spectacular scenery from the Taihang Mountains and Yellow River. Hukou Waterfall is the most magnificent cascade on the Yellow River."},
    business:{zh:"山西是中国重要的能源重化工基地，煤炭储量居全国前列。近年来积极推动能源转型，发展新能源和文旅经济。",py:"Shānxī shì Zhōngguó zhòngyào de néngyuán zhòng huàgōng jīdì, méitàn chǔliàng jū quánguó qiánliè. Jìnniánlái jījí tuīdòng néngyuán zhuǎnxíng, fāzhǎn xīn néngyuán hé wénlǚ jīngjì.",en:"Shanxi is a major energy and chemical base with coal reserves among the nation's highest, now actively promoting energy transition and new energy development."},
    language:{zh:"山西方言属于晋语，是汉语七大方言之一，保留了大量入声。太原话和运城话差别很大，各地方言差异显著。",py:"Shānxī fāngyán shǔyú Jìnyǔ, shì Hànyǔ qī dà fāngyán zhīyī, bǎoliúle dàliàng rùshēng. Tàiyuán huà hé Yùnchéng huà chābié hěn dà, gèdì fāngyán chāyì xiǎnzhù.",en:"Shanxi dialect belongs to the Jin group, one of China's seven major dialects, preserving many entering tones with significant regional variations."}
  },
  150000:{
    history:{zh:"内蒙古自治区成立于1947年，是中国最早建立的省级民族自治区。成吉思汗统一蒙古各部，建立了横跨欧亚的蒙古帝国。",py:"Nèiménggǔ Zìzhìqū chénglì yú 1947 nián, shì Zhōngguó zuìzǎo jiànlì de shěngjí mínzú zìzhìqū. Chéngjísīhán tǒngyī Měnggǔ gèbù, jiànlìle héngkuà Ōu-Yà de Měnggǔ Dìguó.",en:"Inner Mongolia Autonomous Region was established in 1947, China's earliest provincial-level ethnic autonomous region. Genghis Khan united the Mongol tribes to build an empire spanning Eurasia."},
    culture:{zh:"内蒙古是蒙古族文化的核心区域，那达慕大会是草原上最盛大的传统节日。马头琴、长调民歌和呼麦是蒙古族艺术的瑰宝。",py:"Nèiménggǔ shì Měnggǔzú wénhuà de héxīn qūyù, Nàdámù Dàhuì shì cǎoyuán shàng zuì shèngdà de chuántǒng jiérì. Mǎtóuqín, chángdiào míngē hé hūmài shì Měnggǔzú yìshù de guībǎo.",en:"Inner Mongolia is the heartland of Mongolian culture. Naadam is the grandest grassland festival. Horse-head fiddle, long-tune songs, and khoomei are Mongolian artistic treasures."},
    literature:{zh:"蒙古族三大历史著作《蒙古秘史》《蒙古源流》《蒙古黄金史》是研究蒙古历史的珍贵文献。尹湛纳希被誉为蒙古族的曹雪芹。",py:"Měnggǔzú sān dà lìshǐ zhùzuò Měnggǔ Bìshǐ, Měnggǔ Yuánliú, Měnggǔ Huángjīnshǐ shì yánjiū Měnggǔ lìshǐ de zhēnguì wénxiàn. Yǐnzhànnàxī bèi yùwéi Měnggǔzú de Cáo Xuěqín.",en:"The three great Mongolian historical works—the Secret History, Origin Stream, and Golden History—are precious documents. Yinzhannaxi is hailed as the Cao Xueqin of the Mongolian people."},
    culinary:{zh:"蒙古族传统饮食以肉和奶制品为主，手把肉、奶茶、奶酪和烤全羊是经典美食。涮羊肉火锅起源于内蒙古草原。",py:"Měnggǔzú chuántǒng yǐnshí yǐ ròu hé nǎizhìpǐn wéi zhǔ, shǒubǎròu, nǎichá, nǎilào hé kǎo quán yáng shì jīngdiǎn měishí. Shuàn yángròu huǒguō qǐyuányú Nèiménggǔ cǎoyuán.",en:"Traditional Mongolian cuisine centers on meat and dairy—hand-held mutton, milk tea, cheese, and roasted whole lamb are classics. Mutton hotpot originated on the grasslands."},
    nature:{zh:"内蒙古拥有中国最大的天然草原呼伦贝尔草原，面积约十万平方公里。巴丹吉林沙漠以世界最高沙山著称。",py:"Nèiménggǔ yōngyǒu Zhōngguó zuìdà de tiānrán cǎoyuán Hūlúnbèi'ěr cǎoyuán, miànjī yuē shí wàn píngfāng gōnglǐ. Bādānjílín shāmò yǐ shìjiè zuìgāo shāshān zhùchēng.",en:"Inner Mongolia has China's largest natural grassland—Hulunbuir, covering about 100,000 square km. Badain Jaran Desert is known for the world's tallest sand dunes."},
    business:{zh:"内蒙古是中国重要的畜牧业基地和能源大区，煤炭、稀土资源储量居全国首位。伊利和蒙牛两大乳企总部均设在呼和浩特。",py:"Nèiménggǔ shì Zhōngguó zhòngyào de xùmùyè jīdì hé néngyuán dàqū, méitàn, xītǔ zīyuán chǔliàng jū quánguó shǒuwèi. Yīlì hé Méngniú liǎng dà rǔqǐ zǒngbù jūn shè zài Hūhéhàotè.",en:"Inner Mongolia is a major pastoral and energy base with the nation's largest coal and rare earth reserves. Yili and Mengniu dairy giants are both headquartered in Hohhot."},
    language:{zh:"内蒙古通行蒙古语和汉语，蒙古文是传统竖写文字。蒙古语属于阿尔泰语系，与突厥语和满语有亲缘关系。",py:"Nèiménggǔ tōngxíng Měnggǔyǔ hé Hànyǔ, Měnggǔwén shì chuántǒng shùxiě wénzì. Měnggǔyǔ shǔyú Ā'ěrtài yǔxì, yǔ Tūjuéyǔ hé Mǎnyǔ yǒu qīnyuán guānxì.",en:"Mongolian and Chinese are spoken in Inner Mongolia with traditional vertical Mongolian script. Mongolian belongs to the Altaic language family."}
  },
  210000:{
    history:{zh:"辽宁是清朝的发祥地，沈阳故宫和清福陵、清昭陵是世界文化遗产。九一八事变在此爆发，辽宁也是中国工业化的先驱之地。",py:"Liáoníng shì Qīngcháo de fāxiángdì, Shěnyáng Gùgōng hé Qīng Fúlíng, Qīng Zhāolíng shì shìjiè wénhuà yíchǎn. Jiǔyībā Shìbiàn zài cǐ bàofā, Liáoníng yěshì Zhōngguó gōngyèhuà de xiānqū zhī dì.",en:"Liaoning is the birthplace of the Qing Dynasty. The Shenyang Imperial Palace and Qing tombs are UNESCO World Heritage Sites. It was also a pioneer of China's industrialization."},
    culture:{zh:"辽宁是二人转的故乡，这种民间歌舞在东北三省广受欢迎。大连国际服装节和沈阳国际文化节具有国际影响力。",py:"Liáoníng shì èr rén zhuàn de gùxiāng, zhè zhǒng mínjiān gēwǔ zài Dōngběi sānshěng guǎng shòu huānyíng. Dàlián Guójì Fúzhuāng Jié hé Shěnyáng Guójì Wénhuà Jié jùyǒu guójì yǐngxiǎnglì.",en:"Liaoning is the hometown of errenzhuan, a folk dance popular across the three northeastern provinces. Dalian International Fashion Festival has global influence."},
    literature:{zh:"辽宁文学在中国当代文坛占有重要地位，邓友梅、马原、迟子建等作家在此成长。大连和沈阳是东北文学创作的双核城市。",py:"Liáoníng wénxué zài Zhōngguó dāngdài wéntán zhànyǒu zhòngyào dìwèi, Dèng Yǒuméi, Mǎ Yuán, Chí Zǐjiàn děng zuòjiā zài cǐ chéngzhǎng. Dàlián hé Shěnyáng shì Dōngběi wénxué chuàngzuò de shuānghé chéngshì.",en:"Liaoning literature holds an important position in contemporary Chinese literature, nurturing writers like Deng Youmei and Chi Zijian."},
    culinary:{zh:"辽宁菜系融合了鲁菜传统和满族风味，锅包肉是代表菜式。大连海鲜以鲍鱼、海参闻名，沈阳鸡架是本地特色小吃。",py:"Liáoníng càixì rónghéle Lǔcài chuántǒng hé Mǎnzú fēngwèi, guōbāoròu shì dàibiǎo cài shì. Dàlián hǎixiān yǐ bàoyú, hǎishēn wénmíng, Shěnyáng jījià shì běndì tèsè xiǎochī.",en:"Liaoning cuisine blends Shandong and Manchu traditions with guobaorou as the signature dish. Dalian seafood is renowned for abalone and sea cucumber."},
    nature:{zh:"辽宁海岸线长达2110公里，拥有大连、丹东等海滨城市。千山风景区有'东北明珠'之称。",py:"Liáoníng hǎi'ànxiàn chángdá 2110 gōnglǐ, yōngyǒu Dàlián, Dāndōng děng hǎibīn chéngshì. Qiānshān Fēngjǐngqū yǒu Dōngběi Míngzhū zhī chēng.",en:"Liaoning has 2,110 km of coastline with coastal cities like Dalian and Dandong. Qianshan Scenic Area is called the 'Pearl of the Northeast.'"},
    business:{zh:"辽宁曾是新中国工业的摇篮，创造了无数个第一。大连是东北亚重要的国际航运中心和金融中心。",py:"Liáoníng céng shì Xīn Zhōngguó gōngyè de yáolán, chuàngzàole wúshù gè dì yī. Dàlián shì Dōngběiyà zhòngyào de guójì hángyùn zhōngxīn hé jīnróng zhōngxīn.",en:"Liaoning was the cradle of New China's industry, creating numerous firsts. Dalian is a major international shipping and financial center in Northeast Asia."},
    language:{zh:"辽宁方言属于东北官话，语调幽默豪爽。嘎哈、咋整等特色词汇广泛流传，东北话因影视剧而全国知名。",py:"Liáoníng fāngyán shǔyú Dōngběi guānhuà, yǔdiào yōumò háoshuǎng. Gáhá, Zǎ zhěng děng tèsè cíhuì guǎngfàn liúchuán, Dōngběihuà yīn yǐngshìjù ér quánguó zhīmíng.",en:"Liaoning dialect belongs to Northeast Mandarin with humorous and bold tones. Northeast dialect gained nationwide fame through TV dramas."}
  },
  220000:{
    history:{zh:"吉林简称吉，省名取自吉林乌拉，满语意为沿江之城。渤海国和高句丽政权在此留下了丰富的历史遗迹。",py:"Jílín jiǎnchēng Jí, shěng míng qǔzì Jílín Wūlā, Mǎnyǔ yìwéi yánjiāng zhī chéng. Bóhǎi guó hé Gāogōulì zhèngquán zài cǐ liúxiàle fēngfù de lìshǐ yíjì.",en:"Jilin, abbreviated 'Ji,' derives its name from the Manchu 'Jilin Ula' meaning 'city along the river.' The Bohai Kingdom and Goguryeo left rich historical sites here."},
    culture:{zh:"吉林是朝鲜族文化的重要聚集地，延边朝鲜族自治州是中国最大的朝鲜族聚居区。朝鲜族歌舞、泡菜和米酒文化独具特色。",py:"Jílín shì Cháoxiǎnzú wénhuà de zhòngyào jùjídì, Yánbiān Cháoxiǎnzú Zìzhìzhōu shì Zhōngguó zuìdà de Cháoxiǎnzú jùjūqū. Cháoxiǎnzú gēwǔ, pàocài hé mǐjiǔ wénhuà dú jù tèsè.",en:"Jilin is an important gathering place for Korean ethnic culture. Yanbian Korean Autonomous Prefecture is China's largest Korean community."},
    literature:{zh:"吉林省是中国朝鲜文文学的中心，金学铁、李根全等作家用朝鲜语创作了大量优秀作品。长春电影制片厂出品了众多经典影片。",py:"Jílín shěng shì Zhōngguó Cháoxiǎnwén wénxué de zhōngxīn, Jīn Xuétiě, Lǐ Gēnquán děng zuòjiā yòng Cháoxiǎnyǔ chuàngzuòle dàliàng yōuxiù zuòpǐn. Chángchūn Diànyǐng Zhìpiànchāng chūpǐnle zhòngduō jīngdiǎn yǐngpiàn.",en:"Jilin is the center of Chinese Korean-language literature. Changchun Film Studio produced numerous classic films."},
    culinary:{zh:"延边冷面是吉林最知名的美食，搭配辣白菜和牛肉片。朝鲜族打糕、辣白菜和石锅拌饭也是极具特色的传统美食。",py:"Yánbiān lěngmiàn shì Jílín zuì zhīmíng de měishí, dāpèi là báicài hé niúròu piàn. Cháoxiǎnzú dǎgāo, là báicài hé shíguō bànfàn yěshì jí jù tèsè de chuántǒng měishí.",en:"Yanbian cold noodles are Jilin's most famous dish. Korean rice cakes, kimchi, and stone-pot bibimbap are also distinctive traditional foods."},
    nature:{zh:"长白山天池是中国最大的火山湖，也是松花江的源头。吉林雾凇被誉为'中国四大自然奇观'之一。",py:"Chángbáishān Tiānchí shì Zhōngguó zuìdà de huǒshānhú, yěshì Sōnghuājiāng de yuántóu. Jílín wùsōng bèi yùwéi Zhōngguó sì dà zìrán qíguān zhī yī.",en:"Changbaishan Tianchi is China's largest volcanic lake and the source of the Songhua River. Jilin rime is one of China's four natural wonders."},
    business:{zh:"吉林是中国重要的汽车工业基地，一汽集团诞生于此。长春第一汽车制造厂生产的解放牌卡车标志着新中国汽车工业的开端。",py:"Jílín shì Zhōngguó zhòngyào de qìchē gōngyè jīdì, Yī Qì Jítuán dànshēng yú cǐ. Chángchūn dì yī qìchē zhìzàochǎng shēngchǎn de Jiěfàng pái kǎchē biāozhìzhe Xīn Zhōngguó qìchē gōngyè de kāiduān.",en:"Jilin is a major automotive base where FAW Group was born. The 'Jiefang' trucks from China's First Automobile Works marked the beginning of New China's auto industry."},
    language:{zh:"吉林通行东北官话和朝鲜语，延边地区朝鲜语使用非常普遍。吉林话语调圆润，与辽宁、黑龙江东北话有细微差别。",py:"Jílín tōngxíng Dōngběi guānhuà hé Cháoxiǎnyǔ, Yánbiān dìqū de Cháoxiǎnyǔ shǐyòng fēicháng pǔbiàn. Jílín huà yǔdiào yuánrùn, yǔ Liáoníng, Hēilóngjiāng Dōngběihuà yǒu xìwēi chābié.",en:"Northeast Mandarin and Korean are spoken in Jilin, with Korean widely used in Yanbian. Jilin speech has rounder tones with subtle differences from neighboring provinces."}
  },
  230000:{
    history:{zh:"黑龙江简称黑，是中国最北和最东的省份。金朝发源于此，抗联英雄杨靖宇在此抗击日寇的事迹感天动地。",py:"Hēilóngjiāng jiǎnchēng Hēi, shì Zhōngguó zuìběi hé zuìdōng de shěngfèng. Jīncháo fāyuányú cǐ, Kànglián yīngxióng Yáng Jìngyǔ zài cǐ kàngjī rìkòu de shìjì gǎntiāndòngdì.",en:"Heilongjiang, abbreviated 'Hei,' is China's northernmost and easternmost province. The Jin Dynasty originated here, and hero Yang Jingyu's resistance against Japanese invaders is deeply moving."},
    culture:{zh:"黑龙江有鄂伦春、赫哲等北方少数民族文化，赫哲族鱼皮制作技艺是中国独有的非遗。哈尔滨冰雪节是世界四大冰雪节之一。",py:"Hēilóngjiāng yǒu Èlúnchūn, Hèzhé děng běifāng shǎoshù mínzú wénhuà, Hèzhézú yúpí zhìzuò jìyì shì Zhōngguó dúyǒu de fēiwùzhì wénhuà yíchǎn. Hā'ěrbīn Bīngxuějié shì shìjiè sì dà bīngxuějié zhī yī.",en:"Heilongjiang has Oroqen and Hezhe ethnic cultures. Hezhe fish-skin crafting is China's unique intangible heritage. Harbin Ice and Snow Festival is one of the world's four major winter festivals."},
    literature:{zh:"萧红是黑龙江最著名的现代女作家，《呼兰河传》描绘了东北乡村的动人画卷。迟子建以漠河为背景创作了大量优秀作品。",py:"Xiāo Hóng shì Hēilóngjiāng zuì zhùmíng de xiàndài nǚzuòjiā, Hūlánhé Zhuàn miáohuìle Dōngběi xiāngcūn de dōngrén huàjuàn. Chí Zǐjiàn yǐ Mòhé wéi bèijǐng chuàngzuòle dàliàng yōuxiù zuòpǐn.",en:"Xiao Hong is Heilongjiang's most famous modern female writer, with Tales of Hulan River depicting moving scenes of northeastern village life."},
    culinary:{zh:"东北菜在黑龙江最为正宗，锅包肉、地三鲜、杀猪菜和铁锅炖是代表菜肴。冬季的酸菜白肉血肠是家家户户过冬必备。",py:"Dōngběicài zài Hēilóngjiāng zuìwéi zhèngzōng, guōbāoròu, dì sān xiān, shā zhū cài hé tiěguō dùn shì dàibiǎo càiyáo. Dōngjì de suāncài báiròu xuècháng shì jiājiā hùhù guòdōng bìbèi.",en:"Dongbei cuisine is most authentic in Heilongjiang, with guobaorou and iron-pot stew as signature dishes. Winter sour cabbage stew is a seasonal essential."},
    nature:{zh:"黑龙江拥有中国最大的湿地三江平原湿地，以及五大连池世界地质公园。大兴安岭和小兴安岭是中国最大的原始森林区。",py:"Hēilóngjiāng yōngyǒu Zhōngguó zuìdà de shīdì Sānjiāng Píngyuán shīdì, yǐjí Wǔdàliánchí Shìjiè Dìzhì Gōngyuán. Dà Xīng'ānlǐng hé Xiǎo Xīng'ānlǐng shì Zhōngguó zuìdà de yuánshǐ sēnlínqū.",en:"Heilongjiang has China's largest wetland—Sanjiang Plain—and Wudalianchi Global Geopark. The Greater and Lesser Khingan Ranges form China's largest primeval forest."},
    business:{zh:"黑龙江是中国重要的商品粮基地，粮食总产量居全国首位。大庆油田是中国最大的油田，为国家工业化做出了巨大贡献。",py:"Hēilóngjiāng shì Zhōngguó zhòngyào de shāngpǐn liáng jīdì, liángshí zǒng chǎnliàng jū quánguó shǒuwèi. Dàqìng yóutián shì Zhōngguó zuìdà de yóutián, wèi guójiā gōngyèhuà zuòchūle jùdà gòngxiàn.",en:"Heilongjiang is a major commodity grain base with the nation's highest grain output. Daqing Oilfield is China's largest oilfield."},
    language:{zh:"黑龙江方言是东北官话的典型代表，语调直爽热情。冬季漫长促使人们创造了丰富的方言词汇，如嘎嘎冷形容极寒。",py:"Hēilóngjiāng fāngyán shì Dōngběi guānhuà de diǎnxíng dàibiǎo, yǔdiào zhíshuǎng rèqíng. Dōngjì màncháng cùshǐ rénmen chuàngzàole fēngfù de fāngyán cíhuì, rú gāgā lěng xíngróng jíhán.",en:"Heilongjiang dialect is the typical representative of Northeast Mandarin with straightforward, warm tones. Long winters inspired rich dialect vocabulary."}
  },
  310000:{
    history:{zh:"上海简称沪或申，从小渔村发展成为远东第一大都市。1921年中国共产党在上海成立，外滩万国建筑群见证了近代中国的变迁。",py:"Shànghǎi jiǎnchēng Hù huò Shēn, cóng yī gè xiǎo yúcūn fāzhǎn chéngwéi Yuǎndōng dì yī dà dūshì. 1921 nián Zhōngguó Gòngchǎndǎng zài Shànghǎi chénglì, Wàitān wànguó jiànzhù qún jiànzhèngle jìndài Zhōngguó de biànqiān.",en:"Shanghai, abbreviated 'Hu' or 'Shen,' grew from a small fishing village to the Far East's largest metropolis. The CPC was founded here in 1921."},
    culture:{zh:"上海是中国流行文化的发源地，海派文化融合中西，自成一派。上海电影、话剧和流行音乐对中国都市文化影响深远。",py:"Shànghǎi shì Zhōngguó liúxíng wénhuà de fāyuándì, hǎipài wénhuà rónghé zhōng-xī, zì chéng yī pài. Shànghǎi diànyǐng, huàjù hé liúxíng yīnyuè duì Zhōngguó dūshì wénhuà yǐngxiǎng shēnyuǎn.",en:"Shanghai was the birthplace of Chinese pop culture. Haipai culture blends Chinese and Western elements, profoundly influencing Chinese urban culture."},
    literature:{zh:"上海是中国现代文学出版的中心，鲁迅、茅盾等文坛巨匠曾在此创作。《收获》《上海文学》等杂志至今引领中国文学风潮。",py:"Shànghǎi shì Zhōngguó xiàndài wénxué chūbǎn de zhōngxīn, Lǔ Xùn, Máo Dùn děng wéntán jùjiàng céng zài cǐ chuàngzuò. Shōuhuò, Shànghǎi Wénxué děng zázhì zhìjīn yǐnlǐng Zhōngguó wénxué fēngcháo.",en:"Shanghai was the center of modern Chinese literary publishing, hosting literary giants like Lu Xun and Mao Dun."},
    culinary:{zh:"上海菜以浓油赤酱著称，红烧肉、八宝鸭、腌笃鲜是经典菜肴。南翔小笼包和生煎包是上海最受欢迎的小吃。",py:"Shànghǎi cài yǐ nóng yóu chìjiàng zhùchēng, hóngshāoròu, bābǎoyā, yān dǔ xiān shì jīngdiǎn càiyáo. Nánxiáng xiǎolóngbāo hé shēngjiānbāo shì Shànghǎi zuì shòu huānyíng de xiǎochī.",en:"Shanghai cuisine is known for rich, oily, soy-sauce-heavy flavors. Nanxiang xiaolongbao and pan-fried buns are the most popular snacks."},
    nature:{zh:"上海地处长江入海口，崇明岛是中国第三大岛屿。佘山是上海唯一的自然山林，淀山湖是上海最大的淡水湖。",py:"Shànghǎi dìchù Chángjiāng rùhǎikǒu, Chóngmíng Dǎo shì Zhōngguó dì sān dà dǎoyǔ. Shéshān shì Shànghǎi wéiyī de zìrán shānlín, Diànshān Hú shì Shànghǎi zuìdà de dànshuǐ hú.",en:"Shanghai sits at the Yangtze River estuary. Chongming Island is China's third-largest island. Dianshan Lake is Shanghai's largest freshwater lake."},
    business:{zh:"上海是中国最大的经济中心城市，上海证券交易所是全球最重要的金融市场之一。浦东新区是中国改革开放的标志性成果。",py:"Shànghǎi shì Zhōngguó zuìdà de jīngjì zhōngxīn chéngshì, Shànghǎi Zhèngquàn Jiāoyìsuǒ shì quánqiú zuìzhòngyào de jīnróng shìchǎng zhīyī. Pǔdōng Xīnqū shì Zhōngguó gǎigé kāifàng de biāozhìxìng chéngguǒ.",en:"Shanghai is China's largest economic center, with the Shanghai Stock Exchange among the world's most important financial markets."},
    language:{zh:"上海话属于吴语，是中国最有影响力的方言之一。上海话语调柔和婉转，至今在日常交流中广泛使用。",py:"Shànghǎihuà shǔyú Wúyǔ, shì Zhōngguó zuì jù yǐngxiǎnglì de fāngyán zhīyī. Shànghǎihuà yǔdiào róurué wǎnzhuǎn, zhìjīn zài rìcháng jiāoliú zhōng guǎngfàn shǐyòng.",en:"Shanghai dialect belongs to Wu Chinese, one of China's most influential dialects with soft and melodious tones."}
  },
  320000:{
    history:{zh:"江苏历史悠久，南京曾是六朝古都和明朝开国首都。苏州在明清时期是全国最富庶的城市之一，上有天堂，下有苏杭流传千年。",py:"Jiāngsū lìshǐ yōujiǔ, Nánjīng céng shì liùcháo gǔdū hé Míngcháo kāiguó shǒudū. Sūzhōu zài Míng-Qīng shíqī shì quánguó zuì fùshù de chéngshì zhīyī, shàng yǒu tiāntáng, xià yǒu Sū-Háng liúchuán qiānnián.",en:"Jiangsu has a rich history with Nanjing as capital of six dynasties and the Ming founding. Suzhou was one of the wealthiest cities in Ming-Qing China."},
    culture:{zh:"江苏是昆曲的发源地，苏州园林是世界文化遗产。南京云锦和苏州刺绣是国家级非遗，体现了精湛的手工艺水平。",py:"Jiāngsū shì Kūnqǔ de fāyuándì, Sūzhōu yuányuán shì shìjiè wénhuà yíchǎn. Nánjīng yúnjǐn hé Sūzhōu cìxiù shì guójiā jí fēiwùzhì wénhuà yíchǎn, tǐxiànle jīngzhàn de shǒugōngyì shuǐpíng.",en:"Jiangsu is the birthplace of Kunqu opera. Suzhou Gardens are UNESCO World Heritage Sites. Nanjing brocade and Suzhou embroidery are national intangible heritage."},
    literature:{zh:"江苏是才子之乡，唐伯虎、郑板桥等文人画家辈出。现代江苏文坛有汪曾祺、毕飞宇等重要作家。",py:"Jiāngsū shì cáizǐ zhī xiāng, Táng Bóhǔ, Zhèng Bǎnqiáo děng wénrén huàjiā bèichū. Xiàndài Jiāngsū wéntán yǒu Wāng Céngqí, Bì Fēiyǔ děng zhòngyào zuòjiā.",en:"Jiangsu is the hometown of scholars, producing literary painters like Tang Bohu and Zheng Banqiao. Contemporary writers include Wang Zengqi and Bi Feiyu."},
    culinary:{zh:"苏菜是中国四大菜系之一，松鼠桂鱼、清炖蟹粉狮子头等名菜精致典雅。南京盐水鸭、扬州炒饭享誉全国。",py:"Sūcài shì Zhōngguó sì dà càixì zhī yī, sōngshǔ guìyú, qīngdùn xièfěn shīzitóu děng míngcài jīngzhì diǎnyǎ. Nánjīng yánshuǐyā, Yángzhōu chǎofàn xiǎngyù quánguó.",en:"Su cuisine is one of China's four major cuisines. Nanjing salted duck and Yangzhou fried rice are nationally famous."},
    nature:{zh:"江苏地势平坦，太湖是中国五大淡水湖之一，洪泽湖是全国第四大淡水湖。长江和大运河在江苏交汇。",py:"Jiāngsū dìshì píngtǎn, Tàihú shì Zhōngguó wǔ dà dànshuǐhú zhī yī, Hóngzéhú shì quánguó dì sì dà dànshuǐhú. Chángjiāng hé Dà Yùnhé zài Jiāngsū jiāohuì.",en:"Jiangsu has flat terrain with Taihu Lake among China's five largest freshwater lakes and Hongze Lake the fourth largest."},
    business:{zh:"江苏GDP长期位居全国第二，制造业实力雄厚。苏州工业园区是中国与新加坡合作的旗舰项目。",py:"Jiāngsū GDP chángqī wèijū quánguó dì èr, zhìzàoyè shílì xiónghòu. Sūzhōu Gōngyè Yuánqū shì Zhōngguó yǔ Xīnjiāpō hézuò de qíjiàn xiàngmù.",en:"Jiangsu's GDP ranks second nationally with robust manufacturing. Suzhou Industrial Park is a flagship China-Singapore cooperation project."},
    language:{zh:"江苏方言复杂，南北差异巨大。苏南通行吴语，苏州话被誉为吴侬软语；苏北属江淮官话，南京话兼具多种方言特征。",py:"Jiāngsū fāngyán fùzá, nánběi chāyì jùdà. Sūnán tōngxíng Wúyǔ, Sūzhōu huà bèi yùwéi Wú nóng ruǎnyǔ; Sūběi shǔ Jiānghuái guānhuà, Nánjīng huà jiān yǒu duōzhǒng fāngyán tèzhēng.",en:"Jiangsu dialects are complex with huge north-south differences. Southern Jiangsu speaks Wu dialect while northern uses Jianghuai Mandarin."}
  },
  330000:{
    history:{zh:"浙江历史悠久，河姆渡遗址证明七千年前这里就有稻作文明。南宋都城临安是当时世界最繁华的都市。",py:"Zhèjiāng lìshǐ yōujiǔ, Hémǔdù yízhǐ zhèngmíng qīqiān nián qián zhèlǐ jiù yǒu dàozuò wénmíng. Nánsòng dūchéng Lín'ān shì dāngshí shìjiè zuì fánhuá de dūshì.",en:"Zhejiang has a rich history with Hemudu proving rice cultivation 7,000 years ago. The Southern Song capital Lin'an was the world's most prosperous city."},
    culture:{zh:"浙江是越剧和龙泉青瓷的故乡，良渚古城遗址实证了五千年中华文明。杭州西湖和京杭大运河是世界文化遗产。",py:"Zhèjiāng shì Yuèjù hé Lóngquán qīngcí de gùxiāng, Liángzhǔ gǔchéng yízhǐ shízhèngle wǔqiān nián Zhōnghuá wénmíng. Hángzhōu Xīhú hé Jīng-Háng Dà Yùnhé shì shìjiè wénhuà yíchǎn.",en:"Zhejiang is the home of Yue opera and Longquan celadon. Liangzhu archaeological site proves 5,000 years of Chinese civilization. West Lake and the Grand Canal are UNESCO sites."},
    literature:{zh:"浙江是中国文学重镇，鲁迅、郁达夫、艾青等大师级作家均出自浙江。金庸的武侠小说更是华语文学的瑰宝。",py:"Zhèjiāng shì Zhōngguó wénxué zhòngzhèn, Lǔ Xùn, Yù Dáfū, Ài Qīng děng dàshī jí zuòjiā jūn chūzì Zhèjiāng. Jīn Yōng de wǔxiá xiǎoshuō gèng shì huáyǔ wénxué de guībǎo.",en:"Zhejiang is a literary stronghold, home to masters like Lu Xun, Yu Dafu, and Ai Qing. Jin Yong's martial arts novels are treasures of Chinese literature."},
    culinary:{zh:"浙菜以清鲜脆嫩著称，西湖醋鱼、东坡肉、龙井虾仁是杭帮菜经典。宁波汤圆、温州鱼丸各具风味。",py:"Zhècài yǐ qīngxiān cuìnèn zhùchēng, Xīhú cùyú, Dōngpōròu, Lóngjǐng xiārén shì Hángbāng cài jīngdiǎn. Níngbō tāngyuán, Wēnzhōu yúwán gè jù fēngwèi.",en:"Zhejiang cuisine is known for fresh, crisp flavors with West Lake vinegar fish, Dongpo pork, and Longjing shrimp as classics."},
    nature:{zh:"浙江地形以山地丘陵为主，普陀山是中国四大佛教名山之一。雁荡山以奇峰秀水闻名，千岛湖碧波万顷。",py:"Zhèjiāng dìxíng yǐ shāndì qiūlíng wéi zhǔ, Pǔtuóshān shì Zhōngguó sì dà fójiào míngshān zhī yī. Yàndàngshān yǐ qífēng xiùshuǐ wénmíng, Qiāndǎo Hú bō wàn qǐng.",en:"Zhejiang's terrain is mainly mountainous. Mount Putuo is one of China's four sacred Buddhist mountains. Qiandao Lake has vast blue waters."},
    business:{zh:"浙江民营经济发达，义乌小商品市场是全球最大的小商品集散中心。杭州是中国电子商务之都，阿里巴巴总部就设在这里。",py:"Zhèjiāng mínyíng jīngjì fādá, Yìwū xiǎoshāngpǐn shìchǎng shì quánqiú zuìdà de xiǎoshāngpǐn jísàn zhōngxīn. Hángzhōu shì Zhōngguó diànzǐ shāngwù zhī dū, Ālǐbābā zǒngbù jiù shè zài zhèlǐ.",en:"Zhejiang has a thriving private economy. Yiwu is the world's largest small commodities market. Hangzhou is China's e-commerce capital, home to Alibaba."},
    language:{zh:"浙江主要通行吴语，杭州话因南宋迁都带有官话色彩。温州话被称为最难懂的方言，与普通话差异极大。",py:"Zhèjiāng zhǔyào tōngxíng Wúyǔ, Hángzhōu huà yīn Nánsòng qiāndū dàiyǒu guānhuà sècǎi. Wēnzhōu huà bèi chēngwéi zuì nán dǒng de fāngyán, yǔ pǔtōnghuà chāyì jí dà.",en:"Zhejiang mainly speaks Wu dialect. Wenzhou dialect is called the hardest to understand, vastly different from Mandarin."}
  },
  340000:{
    history:{zh:"安徽简称皖，历史上是南北文化交汇之地。凤阳是明太祖朱元璋的家乡，也是中国农村改革的发源地。",py:"Ānhuī jiǎnchēng Wǎn, lìshǐ shàng shì nánběi wénhuà jiāohuì zhī dì. Fèngyáng shì Míng Tàizǔ Zhū Yuánzhāng de jiāxiāng, yěshì Zhōngguó nóngcūn gǎigé de fāyuándì.",en:"Anhui, abbreviated 'Wan,' was a crossroads of northern and southern culture. Fengyang is the hometown of Ming founder Zhu Yuanzhang and birthplace of rural reform."},
    culture:{zh:"徽文化是安徽的文化名片，徽派建筑、徽商文化和新安理学影响深远。黄山、西递宏村是世界文化遗产。",py:"Huī wénhuà shì Ānhuī de wénhuà míngpiàn, Huīpài jiànzhù, Huīshāng wénhuà hé Xīn'ān lǐxué yǐngxiǎng shēnyuǎn. Huángshān, Xīdì-Hóngcūn shì shìjiè wénhuà yíchǎn.",en:"Hui culture is Anhui's cultural hallmark with distinctive architecture and merchant culture. Huangshan and Xidi-Hongcun are UNESCO World Heritage Sites."},
    literature:{zh:"安徽文学源远流长，桐城派是清代影响最大的散文流派。胡适是新文化运动的领袖，陈独秀创办了《新青年》杂志。",py:"Ānhuī wénxué yuányuǎn liúcháng, Tóngchéngpài shì Qīngdài yǐngxiǎng zuìdà de sǎnwén liúpài. Hú Shì shì Xīn Wénhuà Yùndòng de lǐngxiù, Chén Dúxiù chuàngbànle Xīn Qīngnián zázhì.",en:"Anhui's literary tradition runs deep. The Tongcheng School was the most influential prose school in Qing dynasty. Hu Shi and Chen Duxiu were leaders of the New Culture Movement."},
    culinary:{zh:"徽菜是中国八大菜系之一，以重油、重色、重火功著称。臭鳜鱼、毛豆腐和问政山笋是徽菜代表。",py:"Huīcài shì Zhōngguó bā dà càixì zhī yī, yǐ zhòng yóu, zhòng sè, zhòng huǒgōng zhùchēng. Chòu guìyú, máo dòufu hé Wènzhèng shān sǔn shì Huīcài dàibiǎo.",en:"Hui cuisine is one of China's eight great cuisines. Stinky mandarin fish, hairy tofu, and bamboo shoots are signature dishes."},
    nature:{zh:"黄山以奇松、怪石、云海、温泉四绝闻名天下。九华山是中国四大佛教名山之一，天柱山以雄奇险峻著称。",py:"Huángshān yǐ qísōng, guàishí, yúnhǎi, wēnquán sì jué wénmíng tiānxià. Jiǔhuáshān shì Zhōngguó sì dà fójiào míngshān zhī yī, Tiānzhùshān yǐ xióngqí xiǎnjùn zhùchēng.",en:"Huangshan is world-famous for its four wonders: odd pines, grotesque rocks, sea of clouds, and hot springs. Mount Jiuhua is one of China's four sacred Buddhist mountains."},
    business:{zh:"安徽近年经济发展迅速，合肥已成为综合性国家科学中心。奇瑞汽车和科大讯飞是安徽本土成长起来的知名企业。",py:"Ānhuī jìnnián jīngjì fāzhǎn xùnsù, Héféi yǐ chéngwéi zōnghéxìng guójiā kēxué zhōngxīn. Qíruì qìchē hé Kēdà Xùnfēi shì Ānhuī běntǔ chéngzhǎng qǐlái de zhīmíng qǐyè.",en:"Anhui's economy has developed rapidly, with Hefei becoming a comprehensive national science center. Chery and iFlytek are prominent local companies."},
    language:{zh:"安徽方言极为复杂，皖北属中原官话，皖中属江淮官话，皖南则有吴语、徽语等多种方言。",py:"Ānhuī fāngyán jíwéi fùzá, Wǎnběi shǔ Zhōngyuán guānhuà, Wǎnzhōng shǔ Jiānghuái guānhuà, Wǎnnán zé yǒu Wúyǔ, Huīyǔ děng duōzhǒng fāngyán.",en:"Anhui dialects are extremely complex. Northern Anhui speaks Central Plains Mandarin, central uses Jianghuai Mandarin, and southern Anhui has Wu and Hui dialects."}
  },
  350000:{
    history:{zh:"福建简称闽，是海上丝绸之路的起点之一。泉州在宋元时期是世界最大港口，被称为刺桐城。郑成功从福建出发收复了台湾。",py:"Fújiàn jiǎnchēng Mǐn, shì hǎishàng sīchóu zhī lù de qǐdiǎn zhī yī. Quánzhōu zài Sòng-Yuán shíqī shì shìjiè zuìdà gǎngkǒu, bèi chēngwéi Cìtóng Chéng. Zhèngchénggōng cóng Fújiàn chūfā shōufùle Táiwān.",en:"Fujian, abbreviated 'Min,' is a starting point of the Maritime Silk Road. Quanzhou was the world's largest port in Song-Yuan times. Zheng Chenggong launched from Fujian to recover Taiwan."},
    culture:{zh:"福建是闽南文化、客家文化和妈祖文化的核心区域。福建土楼是世界文化遗产，体现了客家人独特的建筑智慧。",py:"Fújiàn shì Mǐnnán wénhuà, Kèjiā wénhuà hé Māzǔ wénhuà de héxīn qūyù. Fújiàn tǔlóu shì shìjiè wénhuà yíchǎn, tǐxiànle Kèjiārén dútè de jiànzhù zhìhuì.",en:"Fujian is the core region for Southern Min, Hakka, and Mazu culture. Fujian Tulou are UNESCO World Heritage Sites reflecting Hakka architectural wisdom."},
    literature:{zh:"福建文学有着深厚底蕴，林语堂、林觉民等文学名家辈出。泉州是联合国教科文组织认定的世界遗产城市。",py:"Fújiàn wénxué yǒuzhe shēnhòu dǐyùn, Lín Yǔtáng, Lín Juémín děng wénxué míngjiā bèichū. Quánzhōu shì Liánhéguó Jiàokēwén Zǔzhī rèndìng de shìjiè yíchǎn chéngshì.",en:"Fujian literature has deep foundations with famous writers like Lin Yutang. Quanzhou is a UNESCO World Heritage City."},
    culinary:{zh:"闽菜是中国八大菜系之一，佛跳墙是闽菜的代表杰作。沙县小吃和福州鱼丸闻名全国，闽南功夫茶文化影响深远。",py:"Mǐncài shì Zhōngguó bā dà càixì zhī yī, Fó tiào qiáng shì Mǐncài de dàibiǎo jiézuò. Shàxiàn xiǎochī hé Fúzhōu yúwán wénmíng quánguó, Mǐnnán gōngfūchá wénhuà yǐngxiǎng shēnyuǎn.",en:"Min cuisine is one of China's eight great cuisines. Buddha Jumps Over the Wall is its masterpiece. Shaxian snacks and Fuzhou fish balls are nationally famous."},
    nature:{zh:"福建森林覆盖率连续多年位居全国首位。武夷山是世界文化与自然双遗产地，太姥山以奇石怪岩著称。",py:"Fújiàn sēnlín fùgàilǜ liánxù duōnián wèijū quánguó shǒuwèi. Wǔyíshān shì shìjiè wénhuà yǔ zìrán shuāng yíchǎndì, Tàimǔshān yǐ qíshí guàiyán zhùchēng.",en:"Fujian's forest coverage rate ranks first nationally. Wuyi Mountain is a UNESCO dual cultural and natural heritage site."},
    business:{zh:"福建是中国民营经济最活跃的省份之一，晋江被誉为中国鞋都。厦门经济特区和福州自贸区是对外开放的重要窗口。",py:"Fújiàn shì Zhōngguó mínyíng jīngjì zuì huóyuè de shěngfèn zhī yī, Jìnjiāng bèi yùwéi Zhōngguó xiédū. Xiàmén jīngjì tèqū hé Fúzhōu zìmàoqū shì duìwài kāifàng de zhòngyào chuāngkǒu.",en:"Fujian has one of China's most vibrant private economies. Jinjiang is called 'China's Shoe Capital.' Xiamen SEZ and Fuzhou FTZ are important opening-up windows."},
    language:{zh:"福建方言极其多样，闽南语、闽东语、闽北语、闽中语和客家话并存。闽南语传播到台湾和东南亚各地。",py:"Fújiàn fāngyán jíqí duōyàng, Mǐnnányǔ, Mǐndōngyǔ, Mǐnběiyǔ, Mǐnzhōngyǔ hé Kèjiāhuà bìngcún. Mǐnnányǔ chuánbō dào Táiwān hé Dōngnányà gèdì.",en:"Fujian dialects are extremely diverse, with Southern Min, Eastern Min, Northern Min, Central Min, and Hakka coexisting. Southern Min spread to Taiwan and Southeast Asia."}
  },
  360000:{
    history:{zh:"江西简称赣，因赣江贯穿全境而得名。南昌起义打响了武装反抗的第一枪，井冈山是中国革命的摇篮。",py:"Jiāngxī jiǎnchēng Gàn, yīn Gàn Jiāng guànchuán quánjìng ér démíng. Nánchāng qìyì dǎxiǎngle wǔzhuāng fǎnkàng de dì yī qiāng, Jǐnggāngshān shì Zhōngguó gémìng de yáolán.",en:"Jiangxi, abbreviated 'Gan,' is named after the Gan River. The Nanchang Uprising fired the first shot of armed resistance. Jinggangshan is the cradle of the Chinese revolution."},
    culture:{zh:"江西是陶瓷文化的圣地，景德镇是中国乃至世界的瓷都，制瓷历史已逾千年。滕王阁与黄鹤楼、岳阳楼并称江南三大名楼。",py:"Jiāngxī shì táocí wénhuà de shèngdì, Jǐngdézhèn shì Zhōngguó nǎizhì shìjiè de cídū, zhìcí lìshǐ yǐ yú qiānnián. Téngwáng Gé yǔ Huánghè Lóu, Yuèyáng Lóu bìng chēng Jiāngnán sān dà mínglóu.",en:"Jiangxi is the holy land of ceramic culture. Jingdezhen is the world's porcelain capital with over a thousand years of history."},
    literature:{zh:"江西文学在中国文学史上占有重要地位，陶渊明是东晋大诗人，开田园诗派之先河。王安石、文天祥也是江西籍杰出文人。",py:"Jiāngxī wénxué zài Zhōngguó wénxué shǐ shàng zhànyǒu zhòngyào dìwèi, Táo Yuānmíng shì Dōngjìn dà shīrén, kāi tiányuán shīpài zhī xiānhé. Wáng Ānshí, Wén Tiānxiáng yěshì Jiāngxī jí jiéchū wénrén.",en:"Jiangxi literature holds an important position. Tao Yuanming pioneered pastoral poetry. Wang Anshi and Wen Tianxiang were also outstanding Jiangxi scholars."},
    culinary:{zh:"赣菜以鲜辣著称，瓦罐汤是江西最具特色的汤品。南昌拌粉、萍乡小炒肉和三杯鸡是赣菜的代表菜肴。",py:"Gàncài yǐ xiānlà zhùchēng, wǎguàn tāng shì Jiāngxī zuìjù tèsè de tāngpǐn. Nánchāng bàn fěn, Píngxiāng xiǎochǎoròu hé sānbēi jī shì Gàncài de dàibiǎo càiyáo.",en:"Gan cuisine is known for fresh spiciness. Clay-pot soup is its most distinctive dish. Nanchang rice noodles and three-cup chicken are Gan signatures."},
    nature:{zh:"江西有庐山、三清山和龙虎山等名山，鄱阳湖是中国最大的淡水湖。婺源油菜花是江西最具代表性的文化符号。",py:"Jiāngxī yǒu Lúshān, Sānqīngshān hé Lónghǔshān děng míngshān, Póyáng Hú shì Zhōngguó zuìdà de dànshuǐ hú. Wùyuán yóucài huā shì Jiāngxī zuìjù dàibiǎo xìng de wénhuà fúhào.",en:"Jiangxi has famous mountains like Lushan and Sanqingshan. Poyang Lake is China's largest freshwater lake. Wuyuan rapeseed flowers are iconic."},
    business:{zh:"江西正在建设内陆开放型经济试验区，电子信息和新能源产业发展迅速。南昌航空城是中国重要的航空产业基地。",py:"Jiāngxī zhèngzài jiànshè nèilù kāifàngxíng jīngjì shìyànqū, diànzǐ xìnxī hé xīn néngyuán chǎnyè fāzhǎn xùnsù. Nánchāng Hángkōng Chéng shì Zhōngguó zhòngyào de hángkōng chǎnyè jīdì.",en:"Jiangxi is building an inland open economic pilot zone. Nanchang Aviation City is an important national aviation industry base."},
    language:{zh:"江西方言属于赣语，是中国七大方言之一。赣语保留了较多古汉语特征，各地方言差异较大。",py:"Jiāngxī fāngyán shǔyú Gànyǔ, shì Zhōngguó qī dà fāngyán zhī yī. Gànyǔ bǎoliúle jiào duō gǔ Hànyǔ tèzhēng, gèdì fāngyán chāyì jiàodà.",en:"Jiangxi dialect belongs to Gan Chinese, one of the seven major dialect groups, preserving many ancient Chinese features."}
  },
  370000:{
    history:{zh:"山东简称鲁，是儒家文化的发源地，孔子和孟子诞生于此。泰山是古代帝王封禅之地，被视为中华文明的精神象征。",py:"Shāndōng jiǎnchēng Lǔ, shì Rújiā wénhuà de fāyuándì, Kǒngzǐ hé Mèngzǐ dànshēng yú cǐ. Tàishān shì gǔdài dìwáng fēngshàn zhī dì, bèi shìwéi Zhōnghuá wénmíng de jīngshén xiàngzhēng.",en:"Shandong, abbreviated 'Lu,' is the birthplace of Confucianism, home to Confucius and Mencius. Mount Tai was the site of imperial worship ceremonies."},
    culture:{zh:"山东是孔孟之乡，曲阜三孔是世界文化遗产。泰山皮影戏和杨家埠木版年画是山东独特的民间艺术。",py:"Shāndōng shì Kǒng-Mèng zhī xiāng, Qūfù Sān Kǒng shì shìjiè wénhuà yíchǎn. Tàishān pǐngyǐngxì hé Yángjiābù mùbǎn niánhuà shì Shāndōng dútè de mínjiān yìshù.",en:"Shandong is the homeland of Confucius and Mencius. Qufu's Three Confucius sites are UNESCO World Heritage Sites."},
    literature:{zh:"山东是中华文学的重镇，蒲松龄的《聊斋志异》是中国古典短篇小说的巅峰之作。《诗经》中多篇作品与山东有关。",py:"Shāndōng shì Zhōnghuá wénxué de zhòngzhèn, Pú Sōnglíng de Liáozhāi Zhìyì shì Zhōngguó gǔdiǎn duǎnpiān xiǎoshuō de diānfēng zhī zuò. Shījīng zhōng duō piān zuòpǐn yǔ Shāndōng yǒuguān.",en:"Shandong is a literary stronghold. Pu Songling's Strange Tales from a Chinese Studio is the pinnacle of classical Chinese short fiction."},
    culinary:{zh:"鲁菜是中国八大菜系之首，以咸鲜为主，讲究火候。糖醋鲤鱼、九转大肠和葱烧海参是鲁菜经典。",py:"Lǔcài shì Zhōngguó bā dà càixì zhī shǒu, yǐ xiánxiān wéi zhǔ, jiǎngjiū huǒhòu. Tángcù lǐyú, Jiǔzhuǎn dàcháng hé Cōngshāo hǎishēn shì Lǔcài jīngdiǎn.",en:"Lu cuisine tops China's eight great cuisines, emphasizing salty-fresh flavors. Sweet-and-sour carp and scallion sea cucumber are classics."},
    nature:{zh:"山东半岛三面环海，崂山是中国海岸线上最高的山峰。趵突泉被誉为天下第一泉，黄河入海口湿地是候鸟天堂。",py:"Shāndōng Bàndǎo sānmiàn huánhǎi, Láoshān shì Zhōngguó hǎi'ànxiàn shàng zuìgāo de shānfēng. Bàotūquán bèi yùwéi tiānxià dì yī quán, Huánghé rùhǎikǒu shīdì shì hòuniǎo tiāntáng.",en:"The Shandong Peninsula is surrounded by sea on three sides. Baotu Spring is called 'First Spring Under Heaven.' The Yellow River estuary is a bird sanctuary."},
    business:{zh:"山东是中国经济第三大省，农业和制造业实力雄厚。青岛啤酒和海尔集团是享誉世界的山东品牌。",py:"Shāndōng shì Zhōngguó jīngjì dì sān dà shěng, nóngyè hé zhìzàoyè shílì xiónghòu. Qīngdǎo píjiǔ hé Hǎi'ěr Jítuán shì xiǎngyù shìjiè de Shāndōng pǐnpái.",en:"Shandong is China's third-largest economy. Tsingtao Beer and Haier Group are Shandong brands known worldwide."},
    language:{zh:"山东话属于北方官话中的冀鲁官话和中原官话，各地口音差异明显。山东人说话直爽豪迈。",py:"Shāndōnghuà shǔyú běifāng guānhuà zhōng de Jì-Lǔ guānhuà hé Zhōngyuán guānhuà, gèdì kǒuyīn chāyì míngxiǎn. Shāndōng rén shuōhuà zhíshuǎng háomài.",en:"Shandong dialect belongs to Ji-Lu and Central Plains Mandarin with distinct regional accents. Shandong people speak directly and boldly."}
  },
  410000:{
    history:{zh:"河南简称豫，地处中原腹地，是中华文明的核心发源地。殷墟是中国最早的都城遗址，甲骨文的发现震惊了世界。",py:"Hénán jiǎnchēng Yù, dìchǔ zhōngyuán fùdì, shì Zhōnghuá wénmíng de héxīn fāxiángdì. Yīnxū shì Zhōngguó zuìzǎo de dūchéng yízhǐ, jiǎgǔwén de fāxiàn zhènjīngle shìjiè.",en:"Henan, abbreviated 'Yu,' lies in the Central Plains heartland, the core birthplace of Chinese civilization. Yinxu is China's earliest capital site, and oracle bone discovery shocked the world."},
    culture:{zh:"河南是少林功夫和太极拳的发源地，少林寺和陈家沟享誉全球。洛阳牡丹甲天下，每年花会吸引数百万游客。",py:"Hénán shì Shàolín gōngfu hé tàijíquán de fāyuándì, Shàolínsì hé Chénjiāgōu xiǎngyù quánqiú. Luòyáng mǔdan jiǎ tiānxià, měinián huāhuì xīyǐn shùbǎi wàn yóukè.",en:"Henan is the birthplace of Shaolin kung fu and tai chi. Luoyang peonies are the finest under heaven, drawing millions to the annual flower festival."},
    literature:{zh:"河南是中国文学的重要发祥地，杜甫、白居易、韩愈等文学巨匠都与河南有深厚渊源。《诗经》和《道德经》诞生于河南。",py:"Hénán shì Zhōngguó wénxué de zhòngyào fāxiángdì, Dù Fǔ, Bái Jūyì, Hán Yù děng wénxué jùjiàng dōu yǔ Hénán yǒu shēnhòu yuānyuán. Shījīng hé Dàodéjīng dànshēng yú Hénán.",en:"Henan is a major birthplace of Chinese literature with Du Fu, Bai Juyi, and Han Yu deeply connected to it. The Book of Songs and Tao Te Ching were born here."},
    culinary:{zh:"豫菜以五味调和为宗旨，胡辣汤是河南最具代表性的早餐。洛阳水席和开封灌汤包是中国饮食文化的瑰宝。",py:"Yùcài yǐ wǔwèi tiáohé wéi zōngzhǐ, húlàtāng shì Hénán zuìjù dàibiǎo xìng de zǎocān. Luòyáng shuǐxí hé Kāifēng guàntāngbāo shì Zhōngguó yǐnshí wénhuà de guībǎo.",en:"Henan cuisine aims for harmony of five flavors. Hulatang is its most representative breakfast. Luoyang water banquet and Kaifeng soup dumplings are food culture treasures."},
    nature:{zh:"河南地处黄河中下游，嵩山是五岳之中岳。云台山世界地质公园以红石峡闻名，鸡公山是中国四大避暑胜地之一。",py:"Hénán dìchú Huánghé zhōngxiàyóu, Sōngshān shì Wǔyuè zhī Zhōngyuè. Yúntáishān Shìjiè Dìzhì Gōngyuán yǐ Hóngshíxiá wénmíng, Jīgōngshān shì Zhōngguó sì dà bìshǔ shèngdì zhī yī.",en:"Henan lies in the middle-lower Yellow River basin with Songshan as the Central Sacred Peak. Yuntai Mountain Global Geopark is famous for Red Stone Gorge."},
    business:{zh:"河南是中国重要的农业大省和交通枢纽，粮食产量居全国第二。郑州航空港经济综合实验区是中国首个航空经济实验区。",py:"Hénán shì Zhōngguó zhòngyào de nóngyè dàshěng hé jiāotōng shūniǔ, liángshí chǎnliàng jū quánguó dì èr. Zhèngzhōu Hángkōnggǎng jīngjì zōnghé shíyànqū shì Zhōngguó shǒu gè hángkōng jīngjì shíyànqū.",en:"Henan is a major agricultural province and transportation hub. Zhengzhou Airport Economy Zone is China's first aviation economy experimental zone."},
    language:{zh:"河南话属于中原官话，是中国最古老的方言之一。河南话语调亲切幽默，中表示同意或肯定，是标志性用语。",py:"Hénánhuà shǔyú Zhōngyuán guānhuà, shì Zhōngguó zuì gǔlǎo de fāngyán zhī yī. Hénánhuà yǔdiào qīnqiè yōumò, zhōng biǎoshì tóngyì huò kěndìng, shì biāozhìxìng yòngyǔ.",en:"Henan dialect belongs to Central Plains Mandarin, one of China's most ancient dialects. 'Zhong' (okay/agreed) is its iconic expression."}
  },
  420000:{
    history:{zh:"湖北简称鄂，荆楚文化源远流长。曾侯乙编钟出土于随州，证明了两千四百年前中国已有高度发达的音乐文明。武汉曾是辛亥革命首义之城。",py:"Húběi jiǎnchēng È, Jīngchǔ wénhuà yuányuǎn liúcháng. Cēng Hóu Yǐ biānzhōng chūtǔ yú Suízhōu, zhèngmíngle liǎngqiān sìbǎi nián qián Zhōngguó yǐ yǒu gāodù fādá de yīnyuè wénmíng. Wǔhàn céng shì Xīnhài Gémìng shǒuyì zhī chéng.",en:"Hubei, abbreviated 'E,' has a long-standing Jingchu culture. The Zenghouyi bells prove China's highly developed musical civilization 2,400 years ago. Wuhan was the starting point of the 1911 Revolution."},
    culture:{zh:"湖北是楚文化的发祥地，屈原是中国最早的浪漫主义诗人。武当山道教文化深厚，武当武术是中国武术的重要流派。",py:"Húběi shì Chǔwénhuà de fāyuándì, Qū Yuán shì Zhōngguó zuìzǎo de làngmán zhǔyì shīrén. Wǔdāngshān dàojiào wénhuà shēnhòu, Wǔdāng wǔshù shì Zhōngguó wǔshù de zhòngyào liúpài.",en:"Hubei is the birthplace of Chu culture. Qu Yuan was China's earliest romantic poet. Wudang Mountain has deep Taoist culture and martial arts tradition."},
    literature:{zh:"屈原的《离骚》开创了中国浪漫主义文学传统，端午节因纪念屈原而起。武汉大学是中国近代高等教育的发源地之一。",py:"Qū Yuán de Lísāo kāichuàngle Zhōngguó làngmán zhǔyì wénxué chuántǒng, Duānwǔjié yīn jìniàn Qū Yuán ér qǐ. Wǔhàn Dàxué shì Zhōngguó jìndài gāoděng jiàoyù de fāyuándì zhī yī.",en:"Qu Yuan's Li Sao initiated China's romantic literary tradition, and Dragon Boat Festival commemorates him. Wuhan University is a birthplace of modern higher education."},
    culinary:{zh:"湖北菜以蒸菜和汤品著称，武昌鱼是湖北的代表名菜。热干面是武汉最著名的早餐，三鲜豆皮和莲藕排骨汤也是经典。",py:"Húběi cài yǐ zhēngcài hé tāngpǐn zhùchēng, Wǔchāngyú shì Húběi de dàibiǎo míngcài. Rè gānmiàn shì Wǔhàn zuì zhùmíng de zǎocān, sānxiān dòupí hé lián'ǒu páigǔ tāng yěshì jīngdiǎn.",en:"Hubei cuisine is known for steamed dishes and soups. Wuchang fish is the signature dish. Hot dry noodles are Wuhan's most famous breakfast."},
    nature:{zh:"湖北有三峡大坝和神农架等著名景点，神农架是中国首个获得联合国教科文组织三冠王称号的地区。东湖是中国最大的城中湖。",py:"Húběi yǒu Sānxiá Dàbà hé Shénnóngjià děng zhùmíng jǐngdiǎn, Shénnóngjià shì Zhōngguó shǒu gè huòdé Liánhéguó Jiàokēwén Zǔzhī Sān Guàn Wáng chēnghào de dìqū. Dōnghú shì Zhōngguó zuìdà de chéngzhōng hú.",en:"Hubei has the Three Gorges Dam and Shennongjia, China's first UNESCO 'Triple Crown' area. East Lake is China's largest urban lake."},
    business:{zh:"武汉是中部地区最大的城市和经济中心，九省通衢的地理位置使其成为重要的交通枢纽。光谷是中国光电子信息产业的重要基地。",py:"Wǔhàn shì zhōngbù dìqū zuìdà de chéngshì hé jīngjì zhōngxīn, jiǔshěng tōngqú de dìlǐ wèizhì shǐ qí chéngwéi zhòngyào de jiāotōng shūniǔ. Guānggǔ shì Zhōngguó guāng diànzǐ xìnxī chǎnyè de zhòngyào jīdì.",en:"Wuhan is central China's largest city and economic center. Optics Valley is a key base for China's optoelectronics industry."},
    language:{zh:"湖北话属于西南官话和江淮官话，武汉话以爽朗直率著称。搞么斯、过早等词汇极具地方特色。",py:"Húběihuà shǔyú Xīnán guānhuà hé Jiānghuái guānhuà, Wǔhànhuà yǐ shuǎnglǎng zhíshuài zhùchēng. Gǎo mǒsī, Guò zǎo děng cíhuì jí jù dìfāng tèsè.",en:"Hubei dialect belongs to Southwest and Jianghuai Mandarin. Wuhan speech is known for its straightforward and hearty character."}
  },
  430000:{
    history:{zh:"湖南简称湘，是楚文化和湖湘文化的重要组成部分。岳麓书院是中国四大书院之一，千年弦歌不绝。马王堆汉墓出土文物震惊世界。",py:"Húnán jiǎnchēng Xiāng, shì Chǔ wénhuà hé Húxiāng wénhuà de zhòngyào zǔchéng bùfèn. Yuèlù Shūyuàn shì Zhōngguó sì dà shūyuàn zhī yī, qiānnián xiángē bù jué. Mǎwángduī Hàn mù chūtǔ wénwù zhènjīngle shìjiè.",en:"Hunan, abbreviated 'Xiang,' is a vital part of Chu and Huxiang culture. Yuelu Academy is one of China's four great academies. Mawangdui Han tomb artifacts amazed the world."},
    culture:{zh:"湖南是湘绣和花鼓戏的故乡，毛泽东等众多伟人诞生于湖南，红色文化底蕴深厚。",py:"Húnán shì Xiāngxiù hé Huāgǔxì de gùxiāng, Máo Zédōng děng zhòngduō wěirén dànshēng yú Húnán, hóngsè wénhuà dǐyùn shēnhòu.",en:"Hunan is the home of Xiang embroidery and flower drum opera. Mao Zedong and many other great leaders were born here with deep red culture heritage."},
    literature:{zh:"湖南文学在中国文学史上占有重要地位，屈原流放于湖南，写下了不朽篇章。沈从文以湘西为背景创作了《边城》等名著。",py:"Húnán wénxué zài Zhōngguó wénxué shǐ shàng zhànyǒu zhòngyào dìwèi, Qū Yuán liúfàng yú Húnán, xiěxiàle bùxiǔ piānzhāng. Shěn Cóngwén yǐ Xiāngxī wéi bèijǐng chuàngzuòle Biānchéng děng míngzhù.",en:"Hunan literature holds an important place. Qu Yuan was exiled here and wrote immortal works. Shen Congwen created Border Town set in western Hunan."},
    culinary:{zh:"湘菜以辣闻名天下，剁椒鱼头和毛氏红烧肉是湘菜的代表作。长沙臭豆腐和常德米粉是湖南最受欢迎的小吃。",py:"Xiāngcài yǐ là wénmíng tiānxià, duòjiāo yútóu hé Máo shì hóngshāoròu shì Xiāngcài de dàibiǎozuò. Chángshā chòu dòufu hé Chángdé mǐfěn shì Húnán zuì shòu huānyíng de xiǎochī.",en:"Xiang cuisine is famous for its spiciness. Chopped chili fish head and Mao-style braised pork are signature dishes. Changsha stinky tofu and Changde rice noodles are popular snacks."},
    nature:{zh:"湖南有张家界国家森林公园、衡山和洞庭湖等著名景点。张家界奇峰三千，被列为世界地质公园。",py:"Húnán yǒu Zhāngjiājiè Guójiā Sēnlín Gōngyuán, Héngshān hé Dòngtíng Hú děng zhùmíng jǐngdiǎn. Zhāngjiājiè qífēng sānqiān, bèi lièwéi shìjiè dìzhì gōngyuán.",en:"Hunan has Zhangjiajie National Forest Park, Mount Heng, and Dongting Lake. Zhangjiajie's peaks are a UNESCO Global Geopark."},
    business:{zh:"长沙已成为新消费之都，茶颜悦色和文和友等新消费品牌从长沙走向全国。湖南广电是中国传媒产业的重要力量。",py:"Chángshā yǐ chéngwéi xīn xiāofèi zhī dū, Chá Yányuèsè hé Wénhéyǒu děng xīn xiāofèi pǐnpái cóng Chángshā zǒuxiàng quánguó. Húnán Guǎngdiàn shì Zhōngguó chuánméi chǎnyè de zhòngyào lìliàng.",en:"Changsha has become a new consumer capital. Hunan Broadcasting is a major force in China's media industry."},
    language:{zh:"湖南话属于湘语，是七大方言之一。长沙话语调起伏大，霸蛮和恰饭等词汇极具湖南特色。",py:"Húnánhuà shǔyú Xiāngyǔ, shì qī dà fāngyán zhī yī. Chángshā huà yǔdiào qǐfú dà, bàmán hé qià fàn děng cíhuì jí jù Húnán tèsè.",en:"Hunan dialect belongs to Xiang Chinese, one of the seven major dialect groups. Changsha speech has dramatic tonal variations."}
  },
  440000:{
    history:{zh:"广东简称粤，是海上丝绸之路的重要起点。广州自古是中国最重要的对外贸易口岸。孙中山在广东开始了革命事业。",py:"Guǎngdōng jiǎnchēng Yuè, shì hǎishàng sīchóu zhī lù de zhòngyào qǐdiǎn. Guǎngzhōu zìgǔ shì Zhōngguó zuì zhòngyào de duìwài màoyì ànkǒu. Sūn Zhōngshān zài Guǎngdōng kāishǐle gémìng shìyè.",en:"Guangdong, abbreviated 'Yue,' is a key starting point of the Maritime Silk Road. Guangzhou has been China's most important foreign trade port since ancient times."},
    culture:{zh:"广东有粤剧、醒狮和潮州工夫茶等丰富的文化遗产。岭南建筑、骑楼和开平碉楼是中西文化融合的杰出代表。",py:"Guǎngdōng yǒu Yuèjù, Xǐngshī hé Cháozhōu gōngfū chá děng fēngfù de wénhuà yíchǎn. Lǐngnán jiànzhù, qílóu hé Kāipíng diāolóu shì zhōng-xī wénhuà rónghé de jiéchū dàibiǎo.",en:"Guangdong has rich cultural heritage including Cantonese opera, lion dancing, and Chaozhou gongfu tea. Lingnan architecture and Kaiping Diaolou represent East-West cultural fusion."},
    literature:{zh:"广东是中国近现代文学的重要阵地，康有为、梁启超是维新文学的代表。当代广东文学以都市写作和打工文学见长。",py:"Guǎngdōng shì Zhōngguó jìn xiàndài wénxué de zhòngyào zhèndì, Kāng Yǒuwéi, Liáng Qǐchāo shì wéixīn wénxué de dàibiǎo. Dāngdài Guǎngdōng wénxué yǐ dūshì xiězuò hé dǎgōng wénxué jiàncháng.",en:"Guangdong was an important base for modern Chinese literature. Contemporary Guangdong literature excels in urban and migrant worker writing."},
    culinary:{zh:"粤菜是中国八大菜系之一，讲究食材新鲜和烹调精细。白切鸡、烧鹅、虾饺和叉烧包是粤菜和广式早茶的经典。",py:"Yuècài shì Zhōngguó bā dà càixì zhī yī, jiǎngjiū shícái xīnxiān hé pēngtiáo jīngxì. Báiqiē jī, shāo'é, xiājiǎo hé chāshāo bāo shì Yuècài hé Guǎngshì zǎochá de jīngdiǎn.",en:"Cantonese cuisine is one of China's eight great cuisines. Steamed chicken, roast goose, shrimp dumplings, and char siu bao are classics."},
    nature:{zh:"广东地处热带和亚热带，丹霞山是丹霞地貌的命名地。鼎湖山是中国第一个自然保护区，珠江口是中华白海豚的栖息地。",py:"Guǎngdōng dìchǔ rèdài hé yà rèdài, Dānxiáshān shì Dānxiá dìmào de mìngmíng dì. Dǐnghúshān shì Zhōngguó dì yī gè zìrán bǎohùqū, Zhūjiāngkǒu shì Zhōnghuá báihǎitún de qīxīdì.",en:"Guangdong lies in tropical and subtropical zones. Danxia Mountain is the namesake of Danxia landforms. Dinghu Mountain is China's first nature reserve."},
    business:{zh:"广东是中国经济第一大省，GDP连续多年居全国首位。深圳是中国改革开放的窗口，华为、腾讯、比亚迪等巨头均诞生于广东。",py:"Guǎngdōng shì Zhōngguó jīngjì dì yī dà shěng, GDP liánxù duōnián jū quánguó shǒuwèi. Shēnzhèn shì Zhōngguó gǎigé kāifàng de chuāngkǒu, Huáwéi, Téngxùn, Bǐyàdí děng jùtóu jūn dànshēng yú Guǎngdōng.",en:"Guangdong is China's largest economy. Shenzhen is the window of reform, where Huawei, Tencent, and BYD were born."},
    language:{zh:"广东主要通行粤语，粤语是中国七大方言之一，在海外华人社区广泛使用。潮汕话和客家话也是广东重要的方言。",py:"Guǎngdōng zhǔyào tōngxíng Yuèyǔ, Yuèyǔ shì Zhōngguó qī dà fāngyán zhī yī, zài hǎiwài huárén shèqū guǎngfàn shǐyòng. Cháoshànhuà hé Kèjiāhuà yěshì Guǎngdōng zhòngyào de fāngyán.",en:"Cantonese is mainly spoken in Guangdong, one of China's seven major dialects. Teochew and Hakka are also important Guangdong dialects."}
  },
  450000:{
    history:{zh:"广西壮族自治区简称桂，是古代海上丝绸之路的重要节点。灵渠是秦始皇时期修建的水利工程，连接了长江和珠江水系。",py:"Guǎngxī Zhuàngzú Zìzhìqū jiǎnchēng Guì, shì gǔdài hǎishàng sīchóu zhī lù de zhòngyào jiédiǎn. Língqú shì Qínshǐhuáng shíqī xiūjiàn de shuǐlì gōngchéng, liánjiēle Cháng Jiāng hé Zhū Jiāng shuǐxì.",en:"Guangxi, abbreviated 'Gui,' was an important node of the Maritime Silk Road. The Lingqu Canal connected the Yangtze and Pearl River systems."},
    culture:{zh:"广西是壮族文化的核心区域，三月三歌圩是壮族最盛大的传统节日。广西民族歌舞和铜鼓文化独具魅力。",py:"Guǎngxī shì Zhuàngzú wénhuà de héxīn qūyù, Sānyuèsān gēxū shì Zhuàngzú zuì shèngdà de chuántǒng jiérì. Guǎngxī mínzú gēwǔ hé tónggǔ wénhuà dú jù mèilì.",en:"Guangxi is the heartland of Zhuang ethnic culture. The March 3rd Song Festival is the grandest traditional celebration with unique bronze drum culture."},
    literature:{zh:"广西文学在中国当代文坛独树一帜。壮族创世史诗《布洛陀》是重要的民族文学遗产。",py:"Guǎngxī wénxué zài Zhōngguó dāngdài wéntán dúshùyīzhì. Zhuàngzú chuàngshì shǐshī Bùluòtuó shì zhòngyào de mínzú wénxué yíchǎn.",en:"Guangxi literature stands out in contemporary Chinese literary circles. The Zhuang creation epic 'Buluotuo' is an important ethnic literary heritage."},
    culinary:{zh:"桂菜以酸辣鲜香为主，桂林米粉是广西最具代表性的美食。螺蛳粉从柳州走向全国，南宁老友粉也各具风味。",py:"Guìcài yǐ suānlà xiānxiāng wéi zhǔ, Guìlín mǐfěn shì Guǎngxī zuìjù dàibiǎo xìng de měishí. Luósīfěn cóng Liǔzhōu zǒuxiàng quánguó, Nánníng lǎoyǒu fěn yě gè jù fēngwèi.",en:"Gui cuisine features sour, spicy, and fresh flavors. Guilin rice noodles are the most representative dish. Liuzhou snail rice noodles went national."},
    nature:{zh:"广西拥有举世闻名的桂林山水，桂林山水甲天下名不虚传。北海银滩和涠洲岛是中国最美的海岛之一。",py:"Guǎngxī yōngyǒu jǔshì wénmíng de Guìlín shānshuǐ, Guìlín shānshuǐ jiǎ tiānxià míng bù xūchuán. Běihǎi yíntān hé Wéizhōu Dǎo shì Zhōngguó zuì měi de hǎidǎo zhī yī.",en:"Guangxi has world-famous Guilin scenery. Beihai Silver Beach and Weizhou Island are among China's most beautiful islands."},
    business:{zh:"广西是中国面向东盟开放合作的前沿和窗口，中国—东盟博览会永久举办地设在南宁。北部湾经济区是重要增长极。",py:"Guǎngxī shì Zhōngguó miànxiàng Dōngméng kāifàng hézuò de qiányán hé chuāngkǒu, Zhōngguó-Dōngméng Bólǎnhuì yǒngjiǔ jǔbàn dì shè zài Nánníng. Běibùwān jīngjìqū shì zhòngyào zēngzhǎng jí.",en:"Guangxi is China's frontier for ASEAN cooperation, hosting the permanent China-ASEAN Expo in Nanning."},
    language:{zh:"广西通行壮语、粤语、桂柳话等多种语言。壮语是中国最大的少数民族语言，使用人口超过一千六百万。",py:"Guǎngxī tōngxíng Zhuàngyǔ, Yuèyǔ, Guìliǔhuà děng duōzhǒng yǔyán. Zhuàngyǔ shì Zhōngguó zuìdà de shǎoshù mínzú yǔyán, shǐyòng rénkǒu chāoguò yīqiān liùbǎi wàn.",en:"Guangxi speaks Zhuang, Cantonese, and Guilin-Liuzhou Mandarin. Zhuang is China's largest minority language with over 16 million speakers."}
  },
  460000:{
    history:{zh:"海南是中国最南端的省份，汉代即设珠崖、儋耳两郡。苏东坡被贬谪至此，留下了丰富的文化遗产。",py:"Hǎinán shì Zhōngguó zuìnánduān de shěngfèng, Hàndài jí shè Zhūyá, Dān'ěr liǎng jùn. Sū Dōngpō bèi biǎnzhé zhì cǐ, liúxiàle fēngfù de wénhuà yíchǎn.",en:"Hainan is China's southernmost province, established as two commanderies in the Han Dynasty. The exiled poet Su Dongpo left a rich cultural legacy here."},
    culture:{zh:"海南是黎族文化的发源地，黎族织锦是中国最早的棉纺织品之一。海南椰子文化深入日常生活。",py:"Hǎinán shì Lízú wénhuà de fāyuándì, Lízú zhījǐn shì Zhōngguó zuìzǎo de miánfǎngzhīpǐn zhī yī. Hǎinán yēzi wénhuà shēnrù rìcháng shēnghuó.",en:"Hainan is the birthplace of Li ethnic culture. Li brocade is one of China's earliest cotton textiles. Coconut culture pervades daily life."},
    literature:{zh:"海南文学在中国文学版图中有独特地位。古代贬官文学是海南文学的重要组成部分，许多被贬官员在此创作了优秀作品。",py:"Hǎinán wénxué zài Zhōngguó wénxué bǎntú zhōng yǒu dútè dìwèi. Gǔdài biǎnguān wénxué shì Hǎinán wénxué de zhòngyào zǔchéng bùfèn, xǔduō bèi biǎn guānyuán zài cǐ chuàngzuòle yōuxiù zuòpǐn.",en:"Hainan literature has a unique position. Ancient exiled-official literature is an important part of Hainan's literary heritage."},
    culinary:{zh:"海南鸡饭是海南最具代表性的美食，文昌鸡和加积鸭是海南四大名菜之首。海南粉和清补凉是当地最受欢迎的小吃。",py:"Hǎinán jīfàn shì Hǎinán zuìjù dàibiǎo xìng de měishí, Wénchāng jī hé Jiājī yā shì Hǎinán sì dà míngcài zhī shǒu. Hǎinán fěn hé Qīngbǔliáng shì dāngdì zuì shòu huānyíng de xiǎochī.",en:"Hainan chicken rice is the island's most representative dish. Wenchang chicken and Jiaji duck top Hainan's four famous dishes."},
    nature:{zh:"海南是中国唯一的热带岛屿省份，拥有三亚、海口等著名海滨城市。五指山是海南最高峰，热带雨林中栖息着众多珍稀物种。",py:"Hǎinán shì Zhōngguó wéiyī de rèdài dǎoyǔ shěngfèng, yōngyǒu Sānyà, Hǎikǒu děng zhùmíng hǎibīn chéngshì. Wǔzhǐshān shì Hǎinán zuìgāo fēng, rèdài yǔlín zhōng qīxīzhe zhòngduō zhēnxī wùzhǒng.",en:"Hainan is China's only tropical island province. Wuzhi Mountain is the highest peak, with tropical rainforests harboring rare species."},
    business:{zh:"海南自由贸易港是中国最大的经济特区，正在建设具有国际影响力的自由贸易港。旅游业和现代服务业是支柱产业。",py:"Hǎinán Zìyóu Mào Yì Gǎng shì Zhōngguó zuìdà de jīngjì tèqū, zhèngzài jiànshè jùyǒu guójì yǐngxiǎnglì de zìyóu màoyì gǎng. Lǚyóu yè hé xiàndài fúwù yè shì zhīzhù chǎnyè.",en:"Hainan Free Trade Port is China's largest special economic zone. Tourism and modern services are pillar industries."},
    language:{zh:"海南话属于闽南语系，与福建闽南话有密切联系。黎语是黎族的本族语言，各地方言差异较大。",py:"Hǎinánhuà shǔyú Mǐnnán yǔxì, yǔ Fújiàn Mǐnnánhuà yǒu mìqiè liánxì. Líyǔ shì Lízú de běnzú yǔyán, gèdì fāngyán chāyì jiàodà.",en:"Hainan dialect belongs to the Southern Min language family. Li language is the native tongue of the Li people with significant regional variations."}
  },
  500000:{
    history:{zh:"重庆简称渝，是中国四个直辖市之一。重庆是巴渝文化的发祥地，抗战时期作为陪都，经历了艰苦卓绝的八年岁月。",py:"Chóngqìng jiǎnchēng Yú, shì Zhōngguó sì gè zhíxiáshì zhī yī. Chóngqìng shì Bā-Yú wénhuà de fāyuándì, kàngzhàn shíqī zuòwéi péidū, jīnglìngle jiānkǔ zhuójué de bā nián suìyuè.",en:"Chongqing, abbreviated 'Yu,' is one of China's four municipalities. It is the birthplace of Ba-Yu culture and served as the wartime capital."},
    culture:{zh:"重庆是巴渝文化的核心区域，大足石刻是世界文化遗产。重庆火锅文化深入骨髓，国际火锅美食文化节享誉全国。",py:"Chóngqìng shì Bā-Yú wénhuà de héxīn qūyù, Dàzú Shíkè shì shìjiè wénhuà yíchǎn. Chóngqìng huǒguō wénhuà shēnrù gǔsuǐ, guójì huǒguō měishí wénhuà jié xiǎngyù quánguó.",en:"Chongqing is the heart of Ba-Yu culture. Dazu Rock Carvings are a UNESCO World Heritage Site. Hotpot culture runs deep here."},
    literature:{zh:"重庆文学在中国当代文坛有着独特贡献，巴金曾在重庆创作了大量重要作品。",py:"Chóngqìng wénxué zài Zhōngguó dāngdài wéntán yǒuzhe dútè gòngxiàn, Bājīn céng zài Chóngqìng chuàngzuòle dàliàng zhòngyào zuòpǐn.",en:"Chongqing literature has made unique contributions. Ba Jin created many important works here."},
    culinary:{zh:"重庆火锅以麻辣著称，九宫格火锅是经典。重庆小面是市民最喜爱的早餐，酸辣粉和烤鱼也是代表。",py:"Chóngqìng huǒguō yǐ málà zhùchēng, jiǔgōnggé huǒguō shì jīngdiǎn. Chóngqìng xiǎomiàn shì shìmín zuì xǐ'ài de zǎocān, suānlàfěn hé kǎoyú yěshì dàibiǎo.",en:"Chongqing hotpot is famous for its numbing spiciness. Chongqing xiaomian is the citizens' favorite breakfast."},
    nature:{zh:"重庆有长江三峡和武隆喀斯特等世界自然遗产。长江穿城而过形成壮丽景观。",py:"Chóngqìng yǒu Chángjiāng Sānxiá hé Wǔlóng Kāsītè děng shìjiè zìrán yíchǎn. Chángjiāng chuān chéng érguò xíngchéng zhuànglì jǐngguān.",en:"Chongqing has the Three Gorges and Wulong Karst as world natural heritage sites."},
    business:{zh:"重庆是中国西部唯一的直辖市，是重要的现代制造业基地。两江新区是国家级新区，电子信息和汽车制造是支柱产业。",py:"Chóngqìng shì Zhōngguó xībù wéiyī de zhíxiáshì, shì zhòngyào de xiàndài zhìzàoyè jīdì. Liǎngjiāng Xīnqū shì guójiā jí xīnqū, diànzǐ xìnxī hé qìchē zhìzào shì zhīzhù chǎnyè.",en:"Chongqing is the only municipality in western China and an important manufacturing base. Liangjiang New Area is a national-level zone."},
    language:{zh:"重庆话属于西南官话，语调生动幽默。巴适、安逸等词汇体现了重庆人乐观豁达的性格特点。",py:"Chóngqìnghuà shǔyú Xīnán guānhuà, yǔdiào shēngdòng yōumò. Bāshì, Ānyì děng cíhuì tǐxiànle Chóngqìng rén lèguān huòdá de xìnggé tèdiǎn.",en:"Chongqing dialect belongs to Southwest Mandarin with vivid and humorous tones. 'Bashi' and 'anyi' reflect Chongqing people's optimistic character."}
  },
  510000:{
    history:{zh:"四川简称川或蜀，是中华文明的重要发源地之一。三星堆遗址和金沙遗址的发现，证明了古蜀文明的高度发达。",py:"Sìchuān jiǎnchēng Chuān huò Shǔ, shì Zhōnghuá wénmíng de zhòngyào fāxiángdì zhī yī. Sānxīngduī yízhǐ hé Jīnshā yízhǐ de fāxiàn, zhèngmíngle Gǔ Shǔ wénmíng de gāodù fādá.",en:"Sichuan, abbreviated 'Chuan' or 'Shu,' is a major birthplace of Chinese civilization. Sanxingdui and Jinsha prove the high development of ancient Shu civilization."},
    culture:{zh:"四川是川剧和大熊猫文化的故乡，变脸绝活闻名天下。都江堰和青城山是世界文化遗产。",py:"Sìchuān shì Chuānjù hé dàxióngmāo wénhuà de gùxiāng, biànliǎn juéhuó wénmíng tiānxià. Dūjiāngyàn hé Qīngchéngshān shì shìjiè wénhuà yíchǎn.",en:"Sichuan is the home of Sichuan opera and giant panda culture. Dujiangyan and Mount Qingcheng are UNESCO World Heritage Sites."},
    literature:{zh:"四川文学人才辈出，司马相如、扬雄是汉赋大家，李白生于四川江油。郭沫若、巴金等现代文学巨匠也是四川人。",py:"Sìchuān wénxué réncái bèichū, Sīmǎ Xiāngrú, Yáng Xióng shì Hàn fù dàjiā, Lǐ Bái shēng yú Sìchuān Jiāngyóu. Guō Mòruò, Bājīn děng xiàndài wénxué jùjiàng yěshì Sìchuān rén.",en:"Sichuan has produced many literary talents. Sima Xiangru and Yang Xiong were great Han rhapsodists, and Li Bai was born in Jiangyou."},
    culinary:{zh:"川菜以麻辣著称于世，麻婆豆腐、宫保鸡丁和水煮鱼是川菜经典。成都火锅文化深入日常生活，影响遍及全国。",py:"Chuāncài yǐ málà zhùchēng yú shì, Mápó dòufu, Gōngbǎo jīdīng hé Shuǐzhǔ yú shì Chuāncài jīngdiǎn. Chéngdū huǒguō wénhuà shēnrù rìcháng shēnghuó, yǐngxiǎng biànjí quánguó.",en:"Sichuan cuisine is world-famous for numbing-spicy flavors. Mapo tofu, kung pao chicken, and boiled fish are classics."},
    nature:{zh:"四川有九寨沟、黄龙和峨眉山等世界自然遗产，大熊猫栖息地是全球生物多样性热点区域。",py:"Sìchuān yǒu Jiǔzhàigōu, Huánglóng hé Éméishān děng shìjiè zìrán yíchǎn, dàxióngmāo qīxīdì shì quánqiú shēngwù duōyàngxìng rèdiǎn qūyù.",en:"Sichuan has Jiuzhaigou, Huanglong, and Mount Emei as world natural heritage sites. Giant panda habitats are global biodiversity hotspots."},
    business:{zh:"四川是中国西部经济大省，成都已成为新一线城市。电子信息、装备制造和生物医药是四川的优势产业。",py:"Sìchuān shì Zhōngguó xībù jīngjì dà shěng, Chéngdū yǐ chéngwéi xīn yīxiàn chéngshì. Diànzǐ xìnxī, zhuāngbèi zhìzào hé shēngwù yīyào shì Sìchuān de yōushì chǎnyè.",en:"Sichuan is a major western economy. Chengdu has become a new first-tier city with strong electronics and biotech industries."},
    language:{zh:"四川话属于西南官话，语调生动幽默，极具感染力。安逸、巴适等词汇体现了四川人悠闲的生活态度。",py:"Sìchuānhuà shǔyú Xīnán guānhuà, yǔdiào shēngdòng yōumò, jí jù gǎnrǎnlì. Ānyì, bāshì děng cíhuì tǐxiànle Sìchuān rén yōuxián de shēnghuó tàidù.",en:"Sichuan dialect belongs to Southwest Mandarin with vivid and infectious tones. Expressions like 'anshi' reflect Sichuan people's leisurely lifestyle."}
  },
  520000:{
    history:{zh:"贵州简称黔或贵，明代建省，历史悠久。遵义会议是中国革命的重要转折点，红军长征在此留下了深刻印记。",py:"Guìzhōu jiǎnchēng Qián huò Guì, Míngdài jiànshěng, lìshǐ yōujiǔ. Zūnyì Huìyì shì Zhōngguó gémìng de zhòngyào zhuǎnzhédiǎn, Hóngjūn chángzhēng zài cǐ liúxiàle shēnkè yìnjìn.",en:"Guizhou, abbreviated 'Qian' or 'Gui,' was established in the Ming Dynasty. The Zunyi Conference was a crucial turning point in the Chinese revolution."},
    culture:{zh:"贵州是多民族聚居的省份，苗族、侗族等少数民族文化丰富多彩。苗族银饰和侗族大歌是国家级非物质文化遗产。",py:"Guìzhōu shì duō mínzú jùjū de shěngfèng, Miáozú, Dòngzú děng shǎoshù mínzú wénhuà fēngfù duōcǎi. Miáozú yínshì hé Dòngzú dàgē shì guójiā jí fēiwùzhì wénhuà yíchǎn.",en:"Guizhou is a multi-ethnic province with rich Miao and Dong cultures. Miao silver ornaments and Dong Grand Song are national intangible heritage."},
    literature:{zh:"贵州文学在中国文学版图中逐渐崛起，多民族背景为文学创作提供了独特素材。",py:"Guìzhōu wénxué zài Zhōngguó wénxué bǎntú zhōng zhújiàn juéqǐ, duō mínzú bèijǐng wèi wénxué chuàngzuò tígōngle dútè sùcái.",en:"Guizhou literature is gradually rising in China's literary landscape with unique multi-ethnic creative material."},
    culinary:{zh:"贵州菜以酸辣著称，酸汤鱼是贵州最具代表性的美食。花溪牛肉粉和丝娃娃也是贵州特色小吃。",py:"Guìzhōu cài yǐ suānlà zhùchēng, suāntāngyú shì Guìzhōu zuìjù dàibiǎo xìng de měishí. Huāxī niúròu fěn hé Sīwáwa yěshì Guìzhōu tèsè xiǎochī.",en:"Guizhou cuisine is known for sour and spicy flavors. Sour fish soup is the most representative dish. Huaxi beef noodles and Siwawa are also specialties."},
    nature:{zh:"贵州喀斯特地貌发育完全，黄果树瀑布是中国最大的瀑布之一。荔波小七孔被誉为地球腰带上的绿宝石。",py:"Guìzhōu Kāsītè dìmào fāyù wánquán, Huángguǒshù Pùbù shì Zhōngguó zuìdà de pùbù zhī yī. Lìbō Xiǎo Qīkǒng bèi yùwéi dìqiú yāodài shàng de lǜ bǎoshí.",en:"Guizhou has fully developed karst topography. Huangguoshu Waterfall is one of China's largest. Libo Small Seven Holes is called a green jewel on the earth's belt."},
    business:{zh:"贵州大数据产业发展迅猛，贵阳是中国大数据产业的先行者。茅台酒是贵州最具价值的经济品牌。",py:"Guìzhōu dàshùjù chǎnyè fāzhǎn xùnměng, Guìyáng shì Zhōngguó dàshùjù chǎnyè de xiānxíngzhě. Máotáijiǔ shì Guìzhōu zuì jù jiàzhí de jīngjì pǐnpái.",en:"Guizhou's big data industry has developed rapidly. Moutai liquor is Guizhou's most valuable economic brand."},
    language:{zh:"贵州方言属于西南官话，各地口音差异较大。少数民族语言丰富，苗语、侗语等在部分地区广泛使用。",py:"Guìzhōu fāngyán shǔyú Xīnán guānhuà, gèdì kǒuyīn chāyì jiàodà. Shǎoshù mínzú yǔyán fēngfù, Miáoyǔ, Dòngyǔ děng zài bùfèn dìqū guǎngfàn shǐyòng.",en:"Guizhou dialect belongs to Southwest Mandarin with significant regional variations. Minority languages like Miao and Dong are widely used."}
  },
  530000:{
    history:{zh:"云南简称滇，历史上是南诏国和大理国的所在地。滇池畔的石寨山出土了大量青铜器，证明了古滇国的灿烂文明。",py:"Yúnnán jiǎnchēng Diān, lìshǐ shàng shì Nánzhào Guó hé Dàlǐ Guó de suǒzàidì. Diānchí pàn de Shízhài Shān chūtǔle dàliàng qīngtóngqì, zhèngmíngle Gǔ Diān Guó de cànlàn wénmíng.",en:"Yunnan, abbreviated 'Dian,' was home to the Nanzhao and Dali kingdoms. Shizhaishan beside Dianchi Lake yielded bronzes proving ancient Dian's brilliant civilization."},
    culture:{zh:"云南是中国民族种类最多的省份，25个少数民族创造了丰富多彩的文化。丽江古城和元阳梯田是世界文化遗产。",py:"Yúnnán shì Zhōngguó mínzú zhǒnglèi zuìduō de shěngfèng, 25 gè shǎoshù mínzú chuàngzàle fēngfù duōcǎi de wénhuà. Lìjiāng Gǔchéng hé Yuányáng tītián shì shìjiè wénhuà yíchǎn.",en:"Yunnan has China's most ethnic groups, with 25 minorities creating diverse cultures. Lijiang Old Town and Yuanyang Rice Terraces are UNESCO sites."},
    literature:{zh:"云南文学以多民族特色著称，艾芜、于坚等诗人和作家的作品具有独特的边地风情。纳西族东巴文化中的象形文字是珍贵的文化遗产。",py:"Yúnnán wénxué yǐ duō mínzú tèsè zhùchēng, Ài Wú, Yú Jiān děng shīrén hé zuòjiā de zuòpǐn jùyǒu dútè de biāndì fēngqíng. Nàxīzú Dōngbā wénhuà zhōng de xiàngxíng wénzì shì zhēnguì de wénhuà yíchǎn.",en:"Yunnan literature is known for multi-ethnic characteristics. Naxi Dongba pictographic script is a precious cultural heritage."},
    culinary:{zh:"云南过桥米线是云南最具代表性的美食，汽锅鸡和宣威火腿也极具特色。云南野生菌种类繁多，是美食爱好者的天堂。",py:"Yúnnán guòqiáo mǐxiàn shì Yúnnán zuìjù dàibiǎo xìng de měishí, qìguō jī hé Xuānwēi huǒtuǐ yě jí jù tèsè. Yúnnán yěshēng jūn zhǒnglèi fánduō, shì měishí àihàozhě de tiāntáng.",en:"Yunnan cross-bridge rice noodles are the most representative dish. Yunnan wild mushrooms of many varieties make it a foodie paradise."},
    nature:{zh:"云南有玉龙雪山、梅里雪山、西双版纳热带雨林等著名景观。三江并流是世界自然遗产，生物多样性极其丰富。",py:"Yúnnán yǒu Yùlóng Xuěshān, Méilǐ Xuěshān, Xīshuāngbǎnnà rèdài yǔlín děng zhùmíng jǐngguān. Sānjiāng bìngliú shì shìjiè zìrán yíchǎn, shēngwù duōyàngxìng jíqí fēngfù.",en:"Yunnan has Yulong Snow Mountain, Meili Snow Mountain, and Xishuangbanna tropical rainforest. Three Parallel Rivers is a UNESCO world natural heritage site."},
    business:{zh:"云南是中国面向南亚和东南亚的重要门户，中老铁路的开通促进了国际贸易。烟草、花卉和旅游是云南的支柱产业。",py:"Yúnnán shì Zhōngguó miànxiàng nányà hé dōngnányà de zhòngyào ménhù, Zhōng-Lǎo Tiělù de kāitōng cùjìnle guójì màoyì. Yāncǎo, huāhuì hé lǚyóu shì Yúnnán de zhīzhù chǎnyè.",en:"Yunnan is an important gateway to South and Southeast Asia. The China-Laos Railway promotes international trade. Tobacco, flowers, and tourism are pillar industries."},
    language:{zh:"云南方言属于西南官话，但各地口音差异明显。少数民族语言极为丰富，傣语、彝语、白语等二十余种语言并存。",py:"Yúnnán fāngyán shǔyú Xīnán guānhuà, dàn gèdì kǒuyīn chāyì míngxiǎn. Shǎoshù mínzú yǔyán jíwéi fēngfù, Dǎiyǔ, Yíyǔ, Báiyǔ děng èrshí yú zhǒng yǔyán bìngcún.",en:"Yunnan dialect belongs to Southwest Mandarin with distinct regional accents. Over twenty minority languages including Dai, Yi, and Bai coexist."}
  },
  540000:{
    history:{zh:"西藏自治区简称藏，是藏族文明的核心区域。松赞干布统一西藏，建立了强大的吐蕃王朝。拉萨布达拉宫是藏传佛教的圣地。",py:"Xīzàng Zìzhìqū jiǎnchēng Zàng, shì Zàngzú wénmíng de héxīn qūyù. Sōngzàngānbù tǒngyī Xīzàng, jiànlìle qiángdà de Tǔbō Wángcháo. Lāsà Bùdálāgōng shì Zàngchuán fójiào de shèngdì.",en:"Tibet, abbreviated 'Zang,' is the heartland of Tibetan civilization. Songtsen Gampo unified Tibet and built the powerful Tubo Dynasty. The Potala Palace in Lhasa is a sacred Buddhist site."},
    culture:{zh:"西藏是藏传佛教文化的中心，唐卡、藏戏和锅庄舞是藏族艺术的瑰宝。雪顿节和藏历新年是西藏最重要的传统节日。",py:"Xīzàng shì Zàngchuán fójiào wénhuà de zhōngxīn, Tǎngkǎ, Zàngxì hé Guōzhuāng wǔ shì Zàngzú yìshù de guībǎo. Xuědùn jié hé Zànglì xīnnián shì Xīzàng zuì zhòngyào de chuántǒng jiérì.",en:"Tibet is the center of Tibetan Buddhist culture. Thangka, Tibetan opera, and Guozhuang dance are artistic treasures. Shoton Festival and Tibetan New Year are the most important traditional festivals."},
    literature:{zh:"《格萨尔王传》是世界上最长的史诗，比荷马史诗长数十倍。仓央嘉措的情诗在中国广为传颂，至今仍被人们传唱。",py:"Gésà'ěr Wáng Zhuàn shì shìjiè shàng zuì cháng de shǐshī, bǐ Hémǎ shǐshī cháng shù shí bèi. Cāngyāng Jiācuò de qíngshī zài Zhōngguó guǎng wéi chuánsòng, zhìjīn réng bèi rénmen chuánchàng.",en:"The Epic of King Gesar is the world's longest epic, dozens of times longer than Homer. Tsangyang Gyatso's love poems are widely recited across China."},
    culinary:{zh:"藏族传统饮食以糌粑、酥油茶和牦牛肉为主。青稞酒是藏族人民喜爱的传统饮品，藏面和牦牛肉干也是特色美食。",py:"Zàngzú chuántǒng yǐnshí yǐ zānbā, sūyóuchá hé máoniúròu wéi zhǔ. Qīngkē jiǔ shì Zàngzú rénmín xǐ'ài de chuántǒng yǐnpǐn, Zàngmiàn hé máoniúròu gān yěshì tèsè měishí.",en:"Traditional Tibetan diet centers on tsampa, butter tea, and yak meat. Highland barley wine is a beloved traditional drink."},
    nature:{zh:"西藏有珠穆朗玛峰、纳木错和雅鲁藏布大峡谷等壮丽景观。西藏是中国生物多样性最丰富的地区之一。",py:"Xīzàng yǒu Zhūmùlǎngmǎ Fēng, Nàmùcuò hé Yǎlǔzāngbù Dàxiágǔ děng zhuànglì jǐngguān. Xīzàng shì Zhōngguó shēngwù duōyàngxìng zuì fēngfù de dìqū zhī yī.",en:"Tibet has Mount Everest, Namtso Lake, and the Yarlung Tsangpo Grand Canyon. It is one of China's most biodiverse regions."},
    business:{zh:"西藏经济以旅游业和特色农牧业为主，清洁能源产业正在快速发展。川藏铁路和青藏铁路极大地改善了交通条件。",py:"Xīzàng jīngjì yǐ lǚyóu yè hé tèsè nóngmùyè wéi zhǔ, qīngjié néngyuán chǎnyè zhèngzài kuàisù fāzhǎn. Chuān-Zàng Tiělù hé Qīng-Zàng Tiělù jídà de gǎishànle jiāotōng tiáojiàn.",en:"Tibet's economy centers on tourism and animal husbandry. Clean energy is developing rapidly. The Sichuan-Tibet and Qinghai-Tibet railways greatly improved transportation."},
    language:{zh:"藏语是西藏的主要语言，属于汉藏语系藏缅语族。藏文是世界上历史最悠久的文字之一，有完整的书写和语法体系。",py:"Zàngyǔ shì Xīzàng de zhǔyào yǔyán, shǔyú Hàn-Zàng yǔxì Zàng-Miǎn yǔzú. Zàngwén shì shìjiè shàng lìshǐ zuì yōujiǔ de wénzì zhī yī, yǒu wánzhěng de shūxiě hé yǔfǎ tǐxì.",en:"Tibetan is the main language of Tibet, belonging to the Sino-Tibetan language family. Tibetan script is one of the world's oldest writing systems."}
  },
  610000:{
    history:{zh:"陕西简称陕或秦，是中华文明的重要发祥地。秦始皇统一六国，建立了中国历史上第一个统一的中央集权王朝。西安是十三朝古都。",py:"Shǎnxī jiǎnchēng Shǎn huò Qín, shì Zhōnghuá wénmíng de zhòngyào fāxiángdì. Qínshǐhuáng tǒngyī liùguó, jiànlìle Zhōngguó lìshǐ shàng dì yī gè tǒngyī de zhōngyāng jíquán wángcháo. Xī'ān shì shísān cháo gǔdū.",en:"Shaanxi, abbreviated 'Shan' or 'Qin,' is a major birthplace of Chinese civilization. Qin Shi Huang unified six kingdoms. Xi'an was capital of thirteen dynasties."},
    culture:{zh:"陕西是秦腔和剪纸艺术的故乡，秦始皇兵马俑被誉为世界第八大奇迹。陕西历史博物馆收藏了大量珍贵文物。",py:"Shǎnxī shì Qínqiāng hé jiǎnzhǐ yìshù de gùxiāng, Qínshǐhuáng bīngmǎyǒng bèi yùwéi shìjiè dì bā dà qíjì. Shǎnxī Lìshǐ Bówùguàn shōucángle dàliàng zhēnguì wénwù.",en:"Shaanxi is the home of Qinqiang opera and paper-cutting art. The Terracotta Warriors are called the Eighth Wonder of the World."},
    literature:{zh:"陕西是中国文学重镇，司马迁的《史记》开创了中国纪传体通史的先河。贾平凹、路遥等当代作家的作品影响深远。",py:"Shǎnxī shì Zhōngguó wénxué zhòngzhèn, Sīmǎ Qiān de Shǐjì kāichuàngle Zhōngguó jìzhuàn tǐ tōngshǐ de xiānhé. Jiǎ Píngwā, Lù Yáo děng dāngdài zuòjiā de zuòpǐn yǐngxiǎng shēnyuǎn.",en:"Shaanxi is a literary stronghold. Sima Qian's Records of the Historian pioneered Chinese biographical history. Contemporary writers Jia Pingwa and Lu Yao have lasting influence."},
    culinary:{zh:"陕西面食文化丰富，油泼面、臊子面和肉夹馍是陕西的代表美食。羊肉泡馍和凉皮也是享誉全国的特色小吃。",py:"Shǎnxī miànshí wénhuà fēngfù, yóupōmiàn, sàozimiàn hé ròujiāmó shì Shǎnxī de dàibiǎo měishí. Yángròu pàomó hé liángpí yěshì xiǎngyù quánguó de tèsè xiǎochī.",en:"Shaanxi has rich noodle culture. Oil-splashed noodles, minced meat noodles, and roujiamo are signature dishes. Lamb pita bread and liangpi are nationally famous."},
    nature:{zh:"陕西有华山、太白山等名山，华山以险峻著称于世。秦岭是中国南北地理分界线，生物多样性极其丰富。",py:"Shǎnxī yǒu Huàshān, Tàibái Shān děng míngshān, Huàshān yǐ xiǎnjùn zhùchēng yú shì. Qínlǐng shì Zhōngguó nánběi dìlǐ fēnjièxiàn, shēngwù duōyàngxìng jíqí fēngfù.",en:"Shaanxi has Huashan and Taibai Mountain. Huashan is world-famous for its precipitousness. Qinling is China's north-south geographic dividing line."},
    business:{zh:"陕西是中国重要的科教和国防工业基地，西安是中国重要的航空航天产业基地。三星半导体工厂是陕西最大的外商投资项目。",py:"Shǎnxī shì Zhōngguó zhòngyào de kējiào hé guófáng gōngyè jīdì, Xī'ān shì Zhōngguó zhòngyào de hángkōng hángtiān chǎnyè jīdì. Sānxīng bàndǎntǐ gōngchǎng shì Shǎnxī zuìdà de wàishāng tóuzī xiàngmù.",en:"Shaanxi is an important science, education, and defense industry base. Xi'an is a major aerospace base. Samsung's semiconductor plant is Shaanxi's largest foreign investment."},
    language:{zh:"陕西话属于中原官话，语调浑厚有力。西安话是关中方言的代表，保留了大量古汉语的特征和词汇。",py:"Shǎnxīnhuà shǔyú Zhōngyuán guānhuà, yǔdiào húnhòu yǒulì. Xī'ānhuà shì Guānzhōng fāngyán de dàibiǎo, bǎoliúle dàliàng gǔ Hànyǔ de tèzhēng hé cíhuì.",en:"Shaanxi dialect belongs to Central Plains Mandarin with deep, powerful tones. Xi'an speech represents Guanzhong dialect, preserving many ancient Chinese features."}
  },
  620000:{
    history:{zh:"甘肃简称甘或陇，是古丝绸之路的黄金通道。敦煌莫高窟是世界文化遗产，保存了千年的佛教艺术瑰宝。",py:"Gānsù jiǎnchēng Gān huò Lǒng, shì gǔ sīchóu zhī lù de huángjīn tōngdào. Dūnhuáng Mògāokū shì shìjiè wénhuà yíchǎn, bǎocúnle qiān nián de fójiào yìshù guībǎo.",en:"Gansu, abbreviated 'Gan' or 'Long,' was the golden passage of the ancient Silk Road. The Mogao Caves in Dunhuang are a UNESCO World Heritage Site."},
    culture:{zh:"甘肃是多民族文化交汇之地，敦煌壁画和嘉峪关长城是世界级文化遗产。花儿民歌是流传于甘肃的国家级非遗。",py:"Gānsù shì duō mínzú wénhuà jiāohuì zhī dì, Dūnhuáng bìhuà hé Jiāyùguān Chángchéng shì shìjiè jí wénhuà yíchǎn. Huā'ér míngē shì liúchuán yú Gānsù de guójiā jí fēi.",en:"Gansu is a crossroads of ethnic cultures. Dunhuang murals and Jiayu Great Pass are world-class heritage. Hua'er folk songs are national intangible heritage."},
    literature:{zh:"甘肃文学以丝绸之路文化为特色，西部文学在中国文学版图中独树一帜。",py:"Gānsù wénxué yǐ sīchóu zhī lù wénhuà wéi tèsè, xībù wénxué zài Zhōngguó wénxué bǎntú zhōng dúshùyīzhì.",en:"Gansu literature features Silk Road culture, with western Chinese literature standing out uniquely."},
    culinary:{zh:"兰州牛肉面是甘肃最具代表性的美食，以一清二白三红四绿五黄著称。手抓羊肉和酿皮子也是甘肃特色美食。",py:"Lánzhōu niúròu miàn shì Gānsù zuìjù dàibiǎo xìng de měishí, yǐ yī qīng èr bái sān hóng sì lǜ wǔ huáng zhùchēng. Shǒuzhuā yángròu hé niàngpízi yěshì Gānsù tèsè měishí.",en:"Lanzhou beef noodles are Gansu's most representative dish. Hand-grabbed lamb and niangpi are also distinctive specialties."},
    nature:{zh:"甘肃地形狭长，从东南到西北跨越了多个气候带。鸣沙山月牙泉是沙漠中的奇观，张掖丹霞地貌色彩斑斓。",py:"Gānsù dìxíng xiácháng, cóng dōngnán dào xīběi kuāyuèle duō gè qìhòu dài. Míngshāshān Yuèquánquán shì shāmò zhōng de qíguān, Zhāngyè Dānxiá dìmào sècǎi bānlán.",en:"Gansu's terrain stretches from southeast to northwest across multiple climate zones. Mingsha Mountain and Crescent Moon Spring are desert wonders."},
    business:{zh:"甘肃是丝绸之路经济带的重要节点，风电和光伏发电产业位居全国前列。酒泉卫星发射中心是中国航天的重要基地。",py:"Gānsù shì Sīchóu zhī lù jīngjì dài de zhòngyào jiédiǎn, fēngdiàn hé guāngfú fādiàn chǎnyè wèijū quánguó qiánliè. Jiǔquán wèixīng fāshè zhōngxīn shì Zhōngguó hángtiān de zhòngyào jīdì.",en:"Gansu is a key node on the Silk Road Economic Belt. Wind and solar power industries rank among the nation's top. Jiuquan Satellite Launch Center is a major space base."},
    language:{zh:"甘肃方言复杂，兰新官话和中原官话并存。河西走廊方言与河东方言差异较大，少数民族语言也丰富多彩。",py:"Gānsù fāngyán fùzá, Lán-Xīn guānhuà hé Zhōngyuán guānhuà bìngcún. Héxī zǒuláng fāngyán yǔ Hédōng fāngyán chāyì jiàodà, shǎoshù mínzú yǔyán yě fēngfù duōcǎi.",en:"Gansu dialects are complex, with Lan-Xin and Central Plains Mandarin coexisting. Hexi Corridor speech differs greatly from eastern dialects."}
  },
  630000:{
    history:{zh:"青海简称青，因境内有中国最大的内陆咸水湖青海湖而得名。唐蕃古道是古代汉藏交流的重要通道。",py:"Qīnghǎi jiǎnchēng Qīng, yīn jìngnèi yǒu Zhōngguó zuìdà de nèilù xiánshuǐhú Qīnghǎi Hú ér démíng. Táng-Bō Gǔdào shì gǔdài Hàn-Zàng jiāoliú de zhòngyào tōngdào.",en:"Qinghai, abbreviated 'Qing,' is named after Qinghai Lake, China's largest inland saltwater lake. The Tang-Tubo Ancient Road was an important channel for Han-Tibetan exchange."},
    culture:{zh:"青海是多民族聚居区，藏族、回族、土族等民族文化交融。塔尔寺是中国藏传佛教格鲁派六大寺院之一。",py:"Qīnghǎi shì duō mínzú jùjū qū, Zàngzú, Huízú, Tǔzú děng mínzú wénhuà jiāoróng. Tǎ'ěr Sì shì Zhōngguó Zàngchuán fójiào Gélǔpài liù dà sìyuàn zhī yī.",en:"Qinghai is a multi-ethnic area with Tibetan, Hui, and Tu cultural blending. Kumbum Monastery is one of the six great Gelug monasteries."},
    literature:{zh:"青海文学以高原文化为背景，展现了独特的雪域风情。",py:"Qīnghǎi wénxué yǐ gāoyuán wénhuà wéi bèijǐng, zhǎnxiànle dútè de xuěyù fēngqíng.",en:"Qinghai literature features plateau culture with unique snowland themes."},
    culinary:{zh:"青海美食以牛羊肉和面食为主，手抓羊肉、酸奶和甜醅是青海最具特色的食品。尕面片和青海酿皮也很受欢迎。",py:"Qīnghǎi měishí yǐ niú yángròu hé miànshí wéi zhǔ, shǒuzhuā yángròu, suānnǎi hé tiānpēi shì Qīnghǎi zuìjù tèsè de shípǐn. Gǎ miànpiàn hé Qīnghǎi niàngpí yě hěn shòu huānyíng.",en:"Qinghai food centers on beef, lamb, and noodles. Hand-grabbed lamb, yogurt, and sweet barley are most distinctive."},
    nature:{zh:"青海有青海湖、三江源和可可西里等著名自然景观。三江源是长江、黄河和澜沧江的发源地，被称为中华水塔。",py:"Qīnghǎi yǒu Qīnghǎi Hú, Sānjiāngyuán hé Kěkěxīlǐ děng zhùmíng zìrán jǐngguān. Sānjiāngyuán shì Chángjiāng, Huáng Hé hé Láncāng Jiāng de fāyuándì, bèi chēngwéi Zhōnghuá shuǐtǎ.",en:"Qinghai has Qinghai Lake, Sanjiangyuan, and Hoh Xil. Sanjiangyuan is the source of the Yangtze, Yellow, and Mekong rivers, called China's water tower."},
    business:{zh:"青海盐湖资源丰富，钾盐储量居全国首位。清洁能源产业是青海的优势产业，光伏和风电装机容量增长迅速。",py:"Qīnghǎi yánhú zīyuán fēngfù, jiǎyán chǔliàng jū quánguó shǒuwèi. Qīngjié néngyuán chǎnyè shì Qīnghǎi de yōushì chǎnyè, guāngfú hé fēngdiàn zhuāngjī róngliàng zēngzhǎng xùnsù.",en:"Qinghai is rich in salt lake resources with the nation's largest potassium reserves. Clean energy is a strength with rapidly growing solar and wind capacity."},
    language:{zh:"青海方言属于中原官话和兰新官话，各地区差异较大。藏语、蒙古语和土语等少数民族语言在青海广泛使用。",py:"Qīnghǎi fāngyán shǔyú Zhōngyuán guānhuà hé Lán-Xīn guānhuà, gè dìqū chāyì jiàodà. Zàngyǔ, Měnggǔyǔ hé Tǔyǔ děng shǎoshù mínzú yǔyán zài Qīnghǎi guǎngfàn shǐyòng.",en:"Qinghai dialects belong to Central Plains and Lan-Xin Mandarin. Tibetan, Mongolian, and Tu languages are widely spoken."}
  },
  640000:{
    history:{zh:"宁夏回族自治区简称宁，历史上是西夏王朝的核心区域。西夏文化独具特色，留下了丰富的历史遗产。",py:"Níngxià Huízú Zìzhìqū jiǎnchēng Níng, lìshǐ shàng shì Xīxià Wángcháo de héxīn qūyù. Xīxià wénhuà dú jù tèsè, liúxiàle fēngfù de lìshǐ yíchǎn.",en:"Ningxia Hui Autonomous Region, abbreviated 'Ning,' was the core area of the Western Xia Dynasty with distinctive cultural heritage."},
    culture:{zh:"宁夏是回族文化的重要聚集地，清真寺建筑和回族花儿民歌是重要的文化遗产。贺兰山岩画记录了远古先民的生活。",py:"Níngxià shì Huízú wénhuà de zhòngyào jùjídì, qīngzhēnsì jiànzhù hé Huízú huā'ér míngē shì zhòngyào de wénhuà yíchǎn. Hèlánshān yánhuà jìlùle yuǎngǔ xiānmín de shēnghuó.",en:"Ningxia is an important gathering place for Hui culture. Mosques and Hua'er folk songs are important cultural heritage. Helan Mountain rock art records ancient life."},
    literature:{zh:"宁夏文学以西部风情见长，展现丝绸之路和回族文化的独特魅力。",py:"Níngxià wénxué yǐ xībù fēngqíng jiàncháng, zhǎnxiàn sīchóu zhī lù hé Huízú wénhuà de dútè mèilì.",en:"Ningxia literature excels in western themes, showcasing the unique charm of the Silk Road and Hui culture."},
    culinary:{zh:"宁夏美食以清真菜肴为主，手抓羊肉和烩肉是宁夏最具代表性的美食。宁夏枸杞是全国最优质的枸杞产区。",py:"Níngxià měishí yǐ qīngzhēn càiyáo wéi zhǔ, shǒuzhuā yángròu hé huìròu shì Níngxià zuìjù dàibiǎo xìng de měishí. Níngxià gǒuqǐ shì quánguó zuì yōuzhì de gǒuqǐ chǎnqū.",en:"Ningxia cuisine features halal dishes. Hand-grabbed lamb is the most representative dish. Ningxia produces China's finest goji berries."},
    nature:{zh:"贺兰山是宁夏的天然屏障，阻挡了腾格里沙漠的东扩。沙坡头是中国治沙的典范，实现了人与自然的和谐共处。",py:"Hèlánshān shì Níngxià de tiānrán píngzhàng, zǔdǎngle Ténggélǐ shāmò de dōng kuò. Shāpōtóu shì Zhōngguó zhìshā de diǎnfàn, shíxiànle rén yǔ zìrán de héxié gòngchǔ.",en:"Helan Mountain is Ningxia's natural barrier against Tengger Desert expansion. Shapotou is a model of sand control, achieving harmony between humans and nature."},
    business:{zh:"宁夏是中国重要的枸杞和葡萄酒产区，银川葡萄酒产业发展迅速。宁东能源化工基地是西部重要的能源化工基地。",py:"Níngxià shì Zhōngguó zhòngyào de gǒuqǐ hé pútáojiǔ chǎnqū, Yínchuān pútáojiǔ chǎnyè fāzhǎn xùnsù. Níngdōng néngyuán huàgōng jīdì shì xībù zhòngyào de néngyuán huàgōng jīdì.",en:"Ningxia is a major goji berry and wine production area. The Ningdong Energy and Chemical Base is a major western energy base."},
    language:{zh:"宁夏话属于中原官话银吴片，语调较为平缓。回族群众在日常生活中也使用阿拉伯语词汇。",py:"Níngxiànhuà shǔyú Zhōngyuán guānhuà Yín-Wú piàn, yǔdiào jiàowéi pínghuǎn. Huízú qúnzhòng zài rìcháng shēnghuó zhōng yě shǐyòng Ālābóyǔ cíhuì.",en:"Ningxia dialect belongs to the Yin-Wu branch of Central Plains Mandarin with relatively flat tones. Hui people also use Arabic vocabulary in daily life."}
  },
  650000:{
    history:{zh:"新疆维吾尔自治区简称新，是中国面积最大的省级行政区。丝绸之路在此留下了辉煌的印记，楼兰古国的传说至今令人神往。",py:"Xīnjiāng Wéiwú'ěr Zìzhìqū jiǎnchēng Xīn, shì Zhōngguó miànjī zuìdà de shěngjí xíngzhèngqū. Sīchóu zhī lù zài cǐ liúxiàle huīhuáng de yìnjìn, Lóulán Gǔguó de chuánshuō zhìjīn lìng rén shénwǎng.",en:"Xinjiang Uyghur Autonomous Region, abbreviated 'Xin,' is China's largest provincial-level area. The Silk Road left glorious marks here."},
    culture:{zh:"新疆是多民族文化的交汇地，维吾尔族木卡姆艺术和新疆舞享誉世界。大巴扎是体验新疆民族文化的最佳场所。",py:"Xīnjiāng shì duō mínzú wénhuà de jiāohuì dì, Wéiwú'ěrzú Mùkǎmǔ yìshù hé Xīnjiāng wǔ xiǎngyù shìjiè. Dàbāzhā shì tǐyàn Xīnjiāng mínzú wénhuà de zuì jiā chǎngsuǒ.",en:"Xinjiang is a meeting point of multi-ethnic cultures. Uyghur Muqam art and Xinjiang dance are world-renowned."},
    literature:{zh:"新疆文学以多民族语言创作见长，维吾尔族文学和哈萨克族文学是中国少数民族文学的重要组成部分。",py:"Xīnjiāng wénxué yǐ duō mínzú yǔyán chuàngzuò jiàncháng, Wéiwú'ěrzú wénxué hé Hāsàkèzú wénxué shì Zhōngguó shǎoshù mínzú wénxué de zhòngyào zǔchéng bùfèn.",en:"Xinjiang literature excels in multi-ethnic language creation. Uyghur and Kazakh literature are important components of Chinese minority literature."},
    culinary:{zh:"新疆美食以烤肉和面食为主，烤全羊、大盘鸡和手抓饭是新疆最具代表性的美食。新疆葡萄和哈密瓜举世闻名。",py:"Xīnjiāng měishí yǐ kǎoròu hé miànshí wéi zhǔ, kǎo quán yáng, dàpán jī hé shǒuzhuā fàn shì Xīnjiāng zuìjù dàibiǎo xìng de měishí. Xīnjiāng pútáo hé hāmì guā jǔshì wénmíng.",en:"Xinjiang food centers on grilled meat and noodles. Roasted whole lamb, big-plate chicken, and pilaf are the most representative dishes."},
    nature:{zh:"新疆有天山、昆仑山和阿尔泰山三大山脉，塔克拉玛干沙漠是中国最大的沙漠。天山天池和喀纳斯湖风景绝美。",py:"Xīnjiāng yǒu Tiānshān, Kūnlúnshān hé Ā'ěrtài shān sān dà shānmài, Tǎkèlāmágàn shāmò shì Zhōngguó zuìdà de shāmò. Tiānshān Tiānchí hé Kānàsī Hú fēngjǐng juéměi.",en:"Xinjiang has the Tianshan, Kunlun, and Altai mountain ranges. The Taklamakan is China's largest desert. Tianchi Lake and Kanas Lake have breathtaking scenery."},
    business:{zh:"新疆是中国向西开放的重要门户，中欧班列在此集结发运。棉花、石油和天然气是新疆的重要经济支柱。",py:"Xīnjiāng shì Zhōngguó xiàng xī kāifàng de zhòngyào ménhù, Zhōng-Ōu bānliè zài cǐ jíjié fāyùn. Miánhuā, shíyóu hé tiānránqì shì Xīnjiāng de zhòngyào jīngjì zhīzhù.",en:"Xinjiang is an important gateway for China's westward opening. Cotton, petroleum, and natural gas are key economic pillars."},
    language:{zh:"新疆通行多种语言，维吾尔语、汉语、哈萨克语等并用。维吾尔语属于突厥语系，使用阿拉伯字母书写。",py:"Xīnjiāng tōngxíng duō zhǒng yǔyán, Wéiwú'ěryǔ, Hànyǔ, Hāsàkèyǔ děng bìngyòng. Wéiwú'ěryǔ shǔyú Tūjué yǔxì, shǐyòng Ālābó zìmǔ shūxiě.",en:"Xinjiang uses multiple languages including Uyghur, Chinese, and Kazakh. Uyghur belongs to the Turkic language family, written in Arabic script."}
  },
  710000:{
    history:{zh:"台湾是中国领土不可分割的一部分。三国时期孙权派卫温到达夷洲，这是大陆与台湾交流的最早记载。明清时期大量移民渡海开发台湾。",py:"Táiwān shì Zhōngguó lǐngtǔ bùkě fēngē de yībùfèn. Sānguó shíqī Sūn Quán pài Wèi Wēn dàodá Yīzhōu, zhè shì dàlù yǔ Táiwān jiāoliú de zuìzǎo jìzài. Míng-Qīng shíqī dàliàng yímín dùhǎi kāifā Táiwān.",en:"Taiwan is an inseparable part of China's territory. In the Three Kingdoms period, the earliest recorded exchange between the mainland and Taiwan occurred."},
    culture:{zh:"台湾文化融合了闽南、客家和原住民文化，故宫博物院收藏了大量中华珍贵文物。布农族和阿美族等原住民文化丰富多彩。",py:"Táiwān wénhuà rónghéle Mǐnnán, Kèjiā hé yuánzhùmín wénhuà, Gùgōng Bówùyuàn shōucángle dàliàng Zhōngguó zhēnguì wénwù. Bùnóngzú hé Āměizú děng yuánzhùmín wénhuà fēngfù duōcǎi.",en:"Taiwan culture blends Southern Min, Hakka, and indigenous cultures. The Palace Museum houses countless Chinese treasures."},
    literature:{zh:"台湾当代文学在中国文学中占有重要地位，白先勇、林海音、龙应台等作家享誉华语世界。",py:"Táiwāng dāngdài wénxué zài Zhōngguó wénxué zhōng zhànyǒu zhòngyào dìwèi, Bái Xiānyǒng, Lín Hǎiyīn, Lóng Yìngtái děng zuòjiā xiǎngyù huáyǔ shìjiè.",en:"Contemporary Taiwan literature holds an important position in Chinese literature, with Bai Xianyong and Lung Ying-tai renowned in the Chinese-speaking world."},
    culinary:{zh:"台湾美食融合各地风味，卤肉饭、珍珠奶茶和蚵仔煎是台湾最具代表性的美食。夜市文化是台湾饮食的一大特色。",py:"Táiwān měishí rónghé gèdì fēngwèi, lǔròu fàn, zhēnzhū nǎichá hé ézǎi jiān shì Táiwān zuìjù dàibiǎo xìng de měishí. Yèshì wénhuà shì Táiwān yǐnshí de yī dà tèsè.",en:"Taiwan food blends flavors from everywhere. Braised pork rice, bubble tea, and oyster omelets are the most representative dishes. Night market culture is a major feature."},
    nature:{zh:"台湾有玉山、阿里山和日月潭等著名景点。玉山海拔3952米是台湾最高峰，阿里山以日出和云海闻名。",py:"Táiwān yǒu Yùshān, Ālǐshān hé Rìyuètán děng zhùmíng jǐngdiǎn. Yùshān hǎibá sānqiān jiǔbǎi wǔshí'èr mǐ shì Táiwān zuìgāo fēng, Ālǐshān yǐ rìchū hé yúnhǎi wénmíng.",en:"Taiwan has Yushan, Alishan, and Sun Moon Lake. Yushan at 3,952 meters is Taiwan's highest peak, famous for sunrise and sea of clouds."},
    business:{zh:"台湾半导体产业在全球占据重要地位，台积电是全球最大的芯片代工厂。台湾经济以高科技产业和制造业为核心。",py:"Táiwān bàndǎntǐ chǎnyè zài quánqiú zhànjù zhòngyào dìwèi, Tái Jī Diàn shì quánqiú zuìdà de xīnpiàn dàigōng chǎng. Táiwān jīngjì yǐ gāo kējì chǎnyè hé zhìzàoyè wéi héxīn.",en:"Taiwan's semiconductor industry plays a crucial global role. TSMC is the world's largest chip foundry."},
    language:{zh:"台湾通行国语和闽南语（台语），客家话也有广泛使用。台湾国语带有独特的腔调，融合了闽南语的语法特征。",py:"Táiwān tōngxíng guóyǔ hé Mǐnnányǔ (Táiyǔ), Kèjiāhuà yě yǒu guǎngfàn shǐyòng. Táiwān guóyǔ dàiyǒu dútè de qiāngdiào, rónghéle Mǐnnányǔ de yǔfǎ tèzhēng.",en:"Taiwan uses Mandarin and Southern Min (Taiwanese), with Hakka also widely spoken. Taiwan Mandarin has a distinctive accent influenced by Southern Min."}
  },
  810000:{
    history:{zh:"香港特别行政区简称港，1842年《南京条约》后被英国殖民统治，1997年7月1日回归祖国。香港从一个小渔村发展成为国际大都市。",py:"Xiānggǎng Tèbié Xíngzhèngqū jiǎnchēng Gǎng, 1842 nián Nánjīng Tiáoyuē hòu bèi Yīngguó zhímín tǒngzhì, 1997 nián 7 yuè 1 rì huíguī zǔguó. Xiānggǎng cóng yī gè xiǎo yúcūn fāzhǎn chéngwéi guójì dūshì.",en:"The Hong Kong SAR, abbreviated 'Gang,' was under British colonial rule after the 1842 Treaty of Nanjing, returning to China on July 1, 1997."},
    culture:{zh:"香港是中西文化交融的国际都市，粤剧、长洲太平清醮等传统文化与西方文化和谐共存。香港电影和流行音乐曾影响整个华语世界。",py:"Xiānggǎng shì zhōng-xī wénhuà rónghé de guójì dūshì, Yuèjù, Chángzhōu Tàipíng Qīngjiāo děng chuántǒng wénhuà yǔ xīfāng wénhuà héxié gòngcún. Xiānggǎng diànyǐng hé liúxíng yīnyuè céng yǐngxiǎng zhěnggè huáyǔ shìjiè.",en:"Hong Kong is an international metropolis where Chinese and Western cultures blend harmoniously. Hong Kong cinema and pop music once influenced the entire Chinese-speaking world."},
    literature:{zh:"香港文学是华语文学的重要组成部分，金庸的武侠小说在华语世界影响深远。也斯、西西等作家展现了独特的香港文学风貌。",py:"Xiānggǎng wénxué shì huáyǔ wénxué de zhòngyào zǔchéng bùfèn, Jīn Yōng de wǔxiá xiǎoshuō zài huáyǔ shìjiè yǐngxiǎng shēnyuǎn. Yě Sī, Xī Xī děng zuòjiā zhǎnxiànle dútè de Xiānggǎng wénxué fēngmào.",en:"Hong Kong literature is an important part of Chinese literature. Jin Yong's martial arts novels have deep influence. Unique Hong Kong literary styles are showcased by local writers."},
    culinary:{zh:"香港美食以港式茶餐厅文化闻名于世，叉烧、蛋挞、菠萝油和丝袜奶茶是经典港式美食。",py:"Xiānggǎng měishí yǐ Gǎng shì chátīng wénhuà wénmíng yú shì, chāshāo, dàntà, bōluó yóu hé sīwà nǎichá shì jīngdiǎn Gǎng shì měishí.",en:"Hong Kong food is world-famous for its cha chaan teng culture. Char siu, egg tarts, pineapple buns, and silk stocking milk tea are classic."},
    nature:{zh:"香港虽面积不大，但拥有丰富的自然生态，离岛和郊野公园占全港面积的四分之三。大帽山是香港最高峰。",py:"Xiānggǎng suī miànjī bù dà, dàn yōngyǒu fēngfù de zìrán shēngtài, lídǎo hé jiāoyě gōngyuán zhàn quán gǎng miànjī de sì fēn zhī sān. Dàmào Shān shì Xiānggǎng zuìgāo fēng.",en:"Though small, Hong Kong has rich natural ecology with outlying islands and country parks covering three-quarters of its area."},
    business:{zh:"香港是国际金融中心和自由贸易港，港交所是全球重要的证券交易所。香港是连接中国内地与国际市场的桥梁。",py:"Xiānggǎng shì guójì jīnróng zhōngxīn hé zìyóu màoyì gǎng, Gǎng Jiāosuǒ shì quánqiú zhòngyào de zhèngquàn jiāoyì suǒ. Xiānggǎng shì liánjiē Zhōngguó nèidì yǔ guójì shìchǎng de qiáoliáng.",en:"Hong Kong is an international financial center and free trade port. HKEX is a major global stock exchange. Hong Kong bridges the mainland with international markets."},
    language:{zh:"香港通行粤语、英语和普通话，三语并用是香港的语言特色。港式粤语融入了大量英语借词，形成了独特的语言风格。",py:"Xiānggǎng tōngxíng Yuèyǔ, Yīngyǔ hé Pǔtōnghuà, sānyǔ bìngyòng shì Xiānggǎng de yǔyán tèsè. Gǎng shì Yuèyǔ rónghéle dàliàng Yīngyǔ jiècí, xíngchéngle dútè de yǔyán fēnggé.",en:"Hong Kong uses Cantonese, English, and Mandarin trilingually. Hong Kong Cantonese incorporates many English loanwords."}
  },
  820000:{
    history:{zh:"澳门特别行政区简称澳，1557年起被葡萄牙殖民统治，1999年12月20日回归祖国。澳门是东西方文化交流的桥梁。",py:"Àomén Tèbié Xíngzhèngqū jiǎnchēng Ào, 1557 nián qǐ bèi Pútáoyá zhímín tǒngzhì, 1999 nián 12 yuè 20 rì huíguī zǔguó. Àomén shì dōng-xīfāng wénhuà jiāoliú de qiáoliáng.",en:"The Macau SAR, abbreviated 'Ao,' was under Portuguese colonial rule from 1557, returning to China on December 20, 1999."},
    culture:{zh:"澳门历史城区是世界文化遗产，体现了中葡文化的独特融合。妈祖文化、土生葡人文化和天主教文化在此和谐共存。",py:"Àomén lìshǐ chéngqū shì shìjiè wénhuà yíchǎn, tǐxiànle Zhōng-Pǔ wénhuà de dútè rónghé. Māzǔ wénhuà, Tǔshēng Púrén wénhuà hé Tiānzhǔjiào wénhuà zài cǐ héxié gòngcún.",en:"The Historic Centre of Macao is a UNESCO World Heritage Site reflecting unique Sino-Portuguese cultural fusion."},
    literature:{zh:"澳门文学以中葡双语创作为特色，是华语文学中独特的组成部分。土生葡人文学展现了多元文化的交融。",py:"Àomén wénxué yǐ Zhōng-Pǔ shuāngyǔ chuàngzuò wéi tèsè, shì huáyǔ wénxué zhōng dútè de zǔchéng bùfèn. Tǔshēng Púrén wénxué zhǎnxiànle duōyuán wénhuà de jiāoróng.",en:"Macau literature features bilingual Chinese-Portuguese creation, a unique part of Chinese literature."},
    culinary:{zh:"澳门美食以土生葡菜闻名，非洲鸡、葡国鸡和木糠布丁是经典葡式美食。猪扒包和蛋挞是澳门最受欢迎的街头小吃。",py:"Àomén měishí yǐ Tǔshēng Pú cài wénmíng, Fēizhōu jī, Púguó jī hé Mùkāng bùdīng shì jīngdiǎn Púshì měishí. Zhūpā bāo hé dàntà shì Àomén zuì shòu huānyíng de jiētóu xiǎochī.",en:"Macau food is famous for Macanese-Portuguese cuisine. African chicken, Portuguese chicken, and serradura are classic. Pork chop buns and egg tarts are popular street food."},
    nature:{zh:"澳门面积虽小，但路氹填海区和周边海域拥有丰富的生态资源。大三巴牌坊前的古炮台山见证了澳门四百年的历史变迁。",py:"Àomén miànjī suī xiǎo, dàn Lùdàng tiánhǎi qū hé zhōubiān hǎiyù yōngyǒu fēngfù de shēngtài zīyuán. Dàsānbā páifāng qián de gǔ pàotáishān jiànzhèngle Àomén sìbǎi nián de lìshǐ biànqiān.",en:"Though small, Macau's Cotai reclamation area and surrounding waters have rich ecological resources. The Ruins of St. Paul's witness 400 years of history."},
    business:{zh:"澳门是世界旅游休闲中心，博彩旅游业是澳门经济的支柱产业。横琴粤澳深度合作区是澳门经济多元化发展的重要平台。",py:"Àomén shì shìjiè lǚyóu xiūxián zhōngxīn, bócǎi lǚyóu yè shì Àomén jīngjì de zhīzhù chǎnyè. Héngqín Yuè-Ào shēndù hézuòqū shì Àomén jīngjì duōyuánhuà fāzhǎn de zhòngyào píngtái.",en:"Macau is a world tourism and leisure center. Gaming and tourism are its pillar industries. The Hengqin cooperation zone is key to economic diversification."},
    language:{zh:"澳门通行粤语、普通话和葡萄牙语，三语并用是澳门的语言特色。土生葡语是澳门独有的克里奥尔语。",py:"Àomén tōngxíng Yuèyǔ, Pǔtōnghuà hé Pútáoyáyǔ, sānyǔ bìngyòng shì Àomén de yǔyán tèsè. Tǔshēng Púyǔ shì Àomén dúyǒu de Kèlǐ'ào'ěr yǔ.",en:"Macau uses Cantonese, Mandarin, and Portuguese trilingually. Patuá, a unique Macanese Creole, is an endangered local language."}
  }
};
